#pragma once

#include "..\globals.h"
#include <windows.h>
#include <math.h>
#include <stdio.h>

#include "Engine\\Directx\\DXGraphicEngine.h"
#include "smlib3d\\smd3d.h"
#include "drawsub.h"
#include "smwsock.h"
#include "smPacket.h"
#include "HoBaram\\HoLinkHeader.h"
#include "effectsnd.h"
#include "playsub.h"

#include "sinUtil.h"
#include "sinMonster.h"
#include "sinMain.h"
#include "sinTrade.h"
#include "sinSubMain.h"
#include "sinItem.h"
#include "sinInvenTory.h"
#include "sinCharStatus.h"
#include "sinInterFace.h"
#include "sinShop.h"
#include "sinSkill.h"
#include "sinMessageBox.h"
#include "sin3D.h"
#include "sinEffect.h"
#include "sinEffect2.h"

#include "sinParticle.h"	
#include "sinMsg.h"
#include "sinHelp.h"
#include "sinQuest.h"
#include "sinSkillEffect.h"
#include "sinEvent.h"
#include "sinPublicEffect.h"
#include "AssaUtil.h"
#include "AssaEffect.h"
#include "sinAssaParticle.h"
#include "AssaTestParticle.h"
#include "sinAssaSkillEffect.h"

#include "YameEffect.h"
#include "sinWarpGate.h"
#include "sinHelpPet.h"
#include "sinSOD2.h"
#include "HaQuest.h"
#include "haPremiumItem.h"
#include "sinParkPcBangPet.h"

#include "SkillFunction\\Tempskron.h"
#include "SkillFunction\\Morayion.h"
#include "IniFiles.h"
#include "Settings.h"
#include "HUD\\CustomHud.h"
#include "HUD\\DisplayDamage.h"
#include "Eventos\Invasao.h"
#include "Eventos\Arena.h"
#include "VIP\\VIP.h"
#include "HUD\\InstancesFlag.h"
#include "Quest\QuestWindow.h"
#include "HUD\\RestaureWindow.h"
#include "Globals.h"
#include "Caravana\\Caravana.h"
#include "Eventos\\WarMode.h"
#include "GameCore.h"
#include "..//KillHandler.h"

#include "ZipArchive.h"

#include <ostream>
#include <vector>
#include <list>
#include <map>
#include <functional>
#include <utility>
#include <algorithm>
#include <any>
#include <regex>
#include <memory>
#include <stack>
#include <mutex>
#include <deque>
#include <sstream>
#include <locale>
#include <cctype>
#include <queue>
#include <clocale>
#include <unordered_map>
#include <array>
#include <limits>
#include <chrono>
#include <random>
#include <filesystem>
#include <future>
#include <ShellAPI.h>
#include <tlhelp32.h>
#include <Shobjidl.h>
#include <intrin.h>
#include <Psapi.h>
#include <immintrin.h>
#include <winternl.h>
#include <assert.h>
#include <Shlwapi.h>
#include <winnt.h>
#include <mmsystem.h>
