#pragma once

#define	FACE_MODEL_MAX		8	
#define	HEAREPOTION_MAX		33

char* szModel_FighterFaceName[FACE_MODEL_MAX][HEAREPOTION_MAX] = {
	{

		"char\\tmABCD\\tmh-b01.inf",
		"char\\tmABCD\\tmh-b02.inf",
		"char\\tmABCD\\tmh-b03.inf",
		"char\\tmABCD\\tmh-b04.inf",
		"char\\tmABCD\\tmh-b05.inf",
		"char\\tmABCD\\tmh-b06.inf",
		"char\\tmABCD\\tmh-b07.inf",
		"char\\tmABCD\\tmh-b08.inf",
		"char\\tmABCD\\tmh-b09.inf",
		"char\\tmABCD\\tmh-b10.inf",
		"char\\tmABCD\\tmh-b11.inf",
		"char\\tmABCD\\tmh-b12.inf",
		"char\\tmABCD\\tmh-b13.inf",
		"char\\tmABCD\\TmhB14t.inf",
		"char\\tmABCD\\TmhB15t.inf",
		"char\\tmABCD\\TmhB16t.inf",
		"char\\tmABCD\\TmhB17t.inf",
		"char\\tmABCD\\tmh-b19.inf",
		"char\\tmABCD\\tmh-b20.inf",
		"char\\tmABCD\\tmh-b21.inf",
		"char\\tmABCD\\tmh-b22.inf",
		"char\\tmABCD\\tmh-b23.inf",
		"char\\tmABCD\\Tmh-B24.inf",		// Máscara
		"char\\tmABCD\\Tmh-B25.inf",		// Carneiro
		"char\\tmABCD\\Tmh-B26.inf",		// Cabelinhocom Xuxa
		"char\\tmABCD\\hfighter_02.inf",	// Loiro 1
		"char\\tmABCD\\hfighter_03.inf",	// Loiro 2 Gohan
		"char\\tmABCD\\CartolaFS.inf",		// Cartola
		"char\\tmABCD\\TmhB-18t.inf",		// Bola
		"char\\tmABCD\\Tmh-B99.inf",		// Girafa
		"char\\tmABCD\\fsxmas.inf",			// Natal
		"char\\tmABCD\\CarnivalHatFS.inf",	// Carnaval
		"char\\tmABCD\\Tmh-B27.inf"			// Cabelinhocom Xuxa
	},
	{
		"char\\tmABCD\\tmh-b01a.inf",
		"char\\tmABCD\\tmh-b02a.inf",
		"char\\tmABCD\\tmh-b03a.inf",
		"char\\tmABCD\\tmh-b04a.inf",
		"char\\tmABCD\\tmh-b05a.inf",
		"char\\tmABCD\\tmh-b06a.inf",
		"char\\tmABCD\\tmh-b07a.inf",
		"char\\tmABCD\\tmh-b08a.inf",
		"char\\tmABCD\\tmh-b09a.inf",
		"char\\tmABCD\\tmh-b10a.inf",
		"char\\tmABCD\\tmh-b11a.inf",
		"char\\tmABCD\\tmh-b12a.inf",
		"char\\tmABCD\\tmh-b13a.inf",
		"char\\tmABCD\\TmhB14t.inf" ,
		"char\\tmABCD\\TmhB15t.inf" ,
		"char\\tmABCD\\TmhB16t.inf" ,
		"char\\tmABCD\\TmhB17t.inf" ,
		"char\\tmABCD\\tmh-b19.inf" ,
		"char\\tmABCD\\tmh-b20.inf" ,
		"char\\tmABCD\\tmh-b21.inf" ,
		"char\\tmABCD\\tmh-b22.inf" ,
		"char\\tmABCD\\tmh-b23.inf" ,
		"char\\tmABCD\\Tmh-B24.inf",		// Máscara
		"char\\tmABCD\\Tmh-B25.inf",		// Carneiro
		"char\\tmABCD\\Tmh-B26.inf",		// Cabelinhocom Xuxa
		"char\\tmABCD\\hfighter_02.inf",	// Loiro 1
		"char\\tmABCD\\hfighter_03.inf",	// Loiro 2 Gohan
		"char\\tmABCD\\CartolaFS.inf",		// Cartola
		"char\\tmABCD\\TmhB-18t.inf",		// Bola
		"char\\tmABCD\\Tmh-B99.inf",		// Girafa
		"char\\tmABCD\\fsxmas.inf",			// Natal
		"char\\tmABCD\\CarnivalHatFS.inf",	// Carnaval
		"char\\tmABCD\\Tmh-B27.inf"			// Cabelinhocom Xuxa
	},
	{
		"char\\tmABCD\\tmh_b01b.inf",
		"char\\tmABCD\\tmh_b02b.inf",
		"char\\tmABCD\\tmh_b03b.inf",
		"char\\tmABCD\\tmh_b04b.inf",
		"char\\tmABCD\\tmh_b05b.inf",
		"char\\tmABCD\\tmh_b06b.inf",
		"char\\tmABCD\\tmh_b07b.inf",
		"char\\tmABCD\\tmh_b08b.inf",
		"char\\tmABCD\\tmh_b09b.inf",
		"char\\tmABCD\\tmh_b10b.inf",
		"char\\tmABCD\\tmh_b11b.inf",
		"char\\tmABCD\\tmh_b12b.inf",
		"char\\tmABCD\\tmh_b13b.inf",
		"char\\tmABCD\\TmhB14t.inf" ,
		"char\\tmABCD\\TmhB15t.inf" ,
		"char\\tmABCD\\TmhB16t.inf" ,
		"char\\tmABCD\\TmhB17t.inf" ,
		"char\\tmABCD\\tmh-b19.inf" ,
		"char\\tmABCD\\tmh-b20.inf" ,
		"char\\tmABCD\\tmh-b21.inf" ,
		"char\\tmABCD\\tmh-b22.inf" ,
		"char\\tmABCD\\tmh-b23.inf" ,
		"char\\tmABCD\\Tmh-B24.inf",		// Máscara
		"char\\tmABCD\\Tmh-B25.inf",		// Carneiro
		"char\\tmABCD\\Tmh-B26.inf",		// Cabelinhocom Xuxa
		"char\\tmABCD\\hfighter_02.inf",	// Loiro 1
		"char\\tmABCD\\hfighter_03.inf",	// Loiro 2 Gohan
		"char\\tmABCD\\CartolaFS.inf",		// Cartola
		"char\\tmABCD\\TmhB-18t.inf",		// Bola
		"char\\tmABCD\\Tmh-B99.inf",		// Girafa
		"char\\tmABCD\\fsxmas.inf",			// Natal
		"char\\tmABCD\\CarnivalHatFS.inf",	// Carnaval
		"char\\tmABCD\\Tmh-B27.inf"			// Cabelinhocom Xuxa
	},
	{
		"char\\tmABCD\\tmh-b01c.inf",
		"char\\tmABCD\\tmh-b02c.inf",
		"char\\tmABCD\\tmh-b03c.inf",
		"char\\tmABCD\\tmh-b04c.inf",
		"char\\tmABCD\\tmh-b05c.inf",
		"char\\tmABCD\\tmh-b06c.inf",
		"char\\tmABCD\\tmh-b07c.inf",
		"char\\tmABCD\\tmh-b08c.inf",
		"char\\tmABCD\\tmh-b09c.inf",
		"char\\tmABCD\\tmh-b10c.inf",
		"char\\tmABCD\\tmh-b11c.inf",
		"char\\tmABCD\\tmh-b12c.inf",
		"char\\tmABCD\\tmh-b13c.inf",
		"char\\tmABCD\\TmhB14t.inf" ,
		"char\\tmABCD\\TmhB15t.inf" ,
		"char\\tmABCD\\TmhB16t.inf" ,
		"char\\tmABCD\\TmhB17t.inf" ,
		"char\\tmABCD\\tmh-b19.inf" ,
		"char\\tmABCD\\tmh-b20.inf" ,
		"char\\tmABCD\\tmh-b21.inf" ,
		"char\\tmABCD\\tmh-b22.inf" ,
		"char\\tmABCD\\tmh-b23.inf" ,
		"char\\tmABCD\\Tmh-B24.inf",		// Máscara
		"char\\tmABCD\\Tmh-B25.inf",		// Carneiro
		"char\\tmABCD\\Tmh-B26.inf",		// Cabelinhocom Xuxa
		"char\\tmABCD\\hfighter_02.inf",	// Loiro 1
		"char\\tmABCD\\hfighter_03.inf",	// Loiro 2 Gohan
		"char\\tmABCD\\CartolaFS.inf",		// Cartola
		"char\\tmABCD\\TmhB-18t.inf",		// Bola
		"char\\tmABCD\\Tmh-B99.inf",		// Girafa
		"char\\tmABCD\\fsxmas.inf",			// Natal
		"char\\tmABCD\\CarnivalHatFS.inf",	// Carnaval
		"char\\tmABCD\\Tmh-B27.inf"			// Cabelinhocom Xuxa
	},
	{
		"char\\tmABCD\\tmh-b01d.inf",
		"char\\tmABCD\\tmh-b02d.inf",
		"char\\tmABCD\\tmh-b03d.inf",
		"char\\tmABCD\\tmh-b04d.inf",
		"char\\tmABCD\\tmh-b05d.inf",
		"char\\tmABCD\\tmh-b06d.inf",
		"char\\tmABCD\\tmh-b07d.inf",
		"char\\tmABCD\\tmh-b08d.inf",
		"char\\tmABCD\\tmh-b09d.inf",
		"char\\tmABCD\\tmh-b10d.inf",
		"char\\tmABCD\\tmh-b11d.inf",
		"char\\tmABCD\\tmh-b12d.inf",
		"char\\tmABCD\\tmh-b13d.inf",
		"char\\tmABCD\\TmhB14t.inf" ,
		"char\\tmABCD\\TmhB15t.inf" ,
		"char\\tmABCD\\TmhB16t.inf" ,
		"char\\tmABCD\\TmhB17t.inf" ,
		"char\\tmABCD\\tmh-b19.inf" ,
		"char\\tmABCD\\tmh-b20.inf" ,
		"char\\tmABCD\\tmh-b21.inf" ,
		"char\\tmABCD\\tmh-b22.inf" ,
		"char\\tmABCD\\tmh-b23.inf" ,
		"char\\tmABCD\\Tmh-B24.inf",		// Máscara
		"char\\tmABCD\\Tmh-B25.inf",		// Carneiro
		"char\\tmABCD\\Tmh-B26.inf",		// Cabelinhocom Xuxa
		"char\\tmABCD\\hfighter_02.inf",	// Loiro 1
		"char\\tmABCD\\hfighter_03.inf",	// Loiro 2 Gohan
		"char\\tmABCD\\CartolaFS.inf",		// Cartola
		"char\\tmABCD\\TmhB-18t.inf",		// Bola
		"char\\tmABCD\\Tmh-B99.inf",		// Girafa
		"char\\tmABCD\\fsxmas.inf",			// Natal
		"char\\tmABCD\\CarnivalHatFS.inf",	// Carnaval
		"char\\tmABCD\\Tmh-B27.inf"			// Cabelinhocom Xuxa
	},
	{
		"char\\tmABCD\\tmh-b01b.inf",
		"char\\tmABCD\\tmh-b02b.inf",
		"char\\tmABCD\\tmh-b03b.inf",
		"char\\tmABCD\\tmh-b01b.inf",
		"char\\tmABCD\\tmh-b02b.inf",
		"char\\tmABCD\\tmh-b03b.inf",
		"char\\tmABCD\\tmh-b01b.inf",
		"char\\tmABCD\\tmh-b02b.inf",
		"char\\tmABCD\\tmh-b03b.inf",
		"char\\tmABCD\\tmh-b01b.inf",
		"char\\tmABCD\\tmh-b02b.inf",
		"char\\tmABCD\\tmh-b03b.inf",
		"char\\tmABCD\\tmh-b01b.inf",
		"char\\tmABCD\\tmh-b02b.inf",
		"char\\tmABCD\\tmh-b03b.inf",
		"char\\tmABCD\\tmh-b01b.inf",
		"char\\tmABCD\\tmh-b02b.inf",
		"char\\tmABCD\\tmh-b03b.inf",
		"char\\tmABCD\\tmh-b01b.inf",
		"char\\tmABCD\\tmh-b02b.inf",
		"char\\tmABCD\\tmh-b03b.inf",
		"char\\tmABCD\\tmh-b01b.inf",
		"char\\tmABCD\\Tmh-B24.inf",		// Máscara
		"char\\tmABCD\\Tmh-B25.inf",		// Carneiro
		"char\\tmABCD\\Tmh-B26.inf",		// Cabelinhocom Xuxa
		"char\\tmABCD\\hfighter_02.inf",	// Loiro 1
		"char\\tmABCD\\hfighter_03.inf",	// Loiro 2 Gohan
		"char\\tmABCD\\CartolaFS.inf",		// Cartola
		"char\\tmABCD\\TmhB-18t.inf",		// Bola
		"char\\tmABCD\\Tmh-B99.inf",		// Girafa
		"char\\tmABCD\\fsxmas.inf",			// Natal
		"char\\tmABCD\\CarnivalHatFS.inf",	// Carnaval
		"char\\tmABCD\\Tmh-B27.inf"			// Cabelinhocom Xuxa
	},
	{
		"char\\tmABCD\\tmh-b01t.inf",
		"char\\tmABCD\\tmh-b02t.inf",
		"char\\tmABCD\\tmh-b03t.inf",
		"char\\tmABCD\\tmh-b01t.inf",
		"char\\tmABCD\\tmh-b02t.inf",
		"char\\tmABCD\\tmh-b03t.inf",
		"char\\tmABCD\\tmh-b01t.inf",
		"char\\tmABCD\\tmh-b02t.inf",
		"char\\tmABCD\\tmh-b01t.inf",
		"char\\tmABCD\\tmh-b02t.inf",
		"char\\tmABCD\\tmh-b03t.inf",
		"char\\tmABCD\\tmh-b01t.inf",
		"char\\tmABCD\\tmh-b02t.inf",
		"char\\tmABCD\\tmh-b03t.inf",
		"char\\tmABCD\\tmh-b01t.inf",
		"char\\tmABCD\\tmh-b02t.inf",
		"char\\tmABCD\\tmh-b03t.inf",
		"char\\tmABCD\\tmh-b01t.inf",
		"char\\tmABCD\\tmh-b02t.inf",
		"char\\tmABCD\\tmh-b03t.inf",
		"char\\tmABCD\\tmh-b01t.inf",
		"char\\tmABCD\\tmh-b02t.inf",
		"char\\tmABCD\\Tmh-B24.inf",		// Máscara
		"char\\tmABCD\\Tmh-B25.inf",		// Carneiro
		"char\\tmABCD\\Tmh-B26.inf",		// Cabelinhocom Xuxa
		"char\\tmABCD\\hfighter_02.inf",	// Loiro 1
		"char\\tmABCD\\hfighter_03.inf",	// Loiro 2 Gohan
		"char\\tmABCD\\CartolaFS.inf",		// Cartola
		"char\\tmABCD\\TmhB-18t.inf",		// Bola
		"char\\tmABCD\\Tmh-B99.inf",		// Girafa
		"char\\tmABCD\\fsxmas.inf",			// Natal
		"char\\tmABCD\\CarnivalHatFS.inf",	// Carnaval
		"char\\tmABCD\\Tmh-B27.inf"			// Cabelinhocom Xuxa
	},
	{
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\TmhB-18t.inf",
		"char\\tmABCD\\Tmh-B24.inf",		// Máscara
		"char\\tmABCD\\Tmh-B25.inf",		// Carneiro
		"char\\tmABCD\\Tmh-B26.inf",		// Cabelinhocom Xuxa
		"char\\tmABCD\\hfighter_02.inf",	// Loiro 1
		"char\\tmABCD\\hfighter_03.inf",	// Loiro 2 Gohan
		"char\\tmABCD\\CartolaFS.inf",		// Cartola
		"char\\tmABCD\\TmhB-18t.inf",		// Bola
		"char\\tmABCD\\Tmh-B99.inf",		// Girafa
		"char\\tmABCD\\fsxmas.inf",			// Natal
		"char\\tmABCD\\CarnivalHatFS.inf",	// Carnaval
		"char\\tmABCD\\Tmh-B27.inf"			// Cabelinhocom Xuxa
	}
};

char* szModel_MechFaceName[FACE_MODEL_MAX][HEAREPOTION_MAX] = {
	{
		"char\\tmABCD\\tmh-a01.inf",
		"char\\tmABCD\\tmh-a02.inf",
		"char\\tmABCD\\tmh-a03.inf",
		"char\\tmABCD\\tmh-a04.inf",
		"char\\tmABCD\\tmh-a05.inf",
		"char\\tmABCD\\tmh-a06.inf",
		"char\\tmABCD\\tmh-a07.inf",
		"char\\tmABCD\\tmh-a08.inf",
		"char\\tmABCD\\tmh-a09.inf",
		"char\\tmABCD\\tmh-a10.inf",
		"char\\tmABCD\\tmh-a11.inf",
		"char\\tmABCD\\tmh-a12.inf",
		"char\\tmABCD\\tmh-a13.inf",
		"char\\tmABCD\\TmhA14t.inf",
		"char\\tmABCD\\TmhA15t.inf",
		"char\\tmABCD\\TmhA16t.inf",
		"char\\tmABCD\\TmhA17t.inf",
		"char\\tmABCD\\tmh-a19.inf",
		"char\\tmABCD\\tmh-a20.inf",
		"char\\tmABCD\\tmh-a21.inf",
		"char\\tmABCD\\tmh-a22.inf",
		"char\\tmABCD\\tmh-a23.inf",
		"char\\tmABCD\\Tmh-A24.inf",
		"char\\tmABCD\\Tmh-A25.inf",
		"char\\tmABCD\\Tmh-A26.inf",
		"char\\tmABCD\\hmech_02.inf",
		"char\\tmABCD\\hmech_03.inf",
		"char\\tmABCD\\CartolaMS.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\Tmh-A99.inf",
		"char\\tmABCD\\msxmas.inf",
		"char\\tmABCD\\CarnivalHatMS.inf",
		"char\\tmABCD\\Tmh-A27.inf"
	},
	{
		"char\\tmABCD\\tmh-a01a.inf",
		"char\\tmABCD\\tmh-a02a.inf",
		"char\\tmABCD\\tmh-a03a.inf",
		"char\\tmABCD\\tmh-a04a.inf",
		"char\\tmABCD\\tmh-a05a.inf",
		"char\\tmABCD\\tmh-a06a.inf",
		"char\\tmABCD\\tmh-a07a.inf",
		"char\\tmABCD\\tmh-a08a.inf",
		"char\\tmABCD\\tmh-a09a.inf",
		"char\\tmABCD\\tmh-a10a.inf",
		"char\\tmABCD\\tmh-a11a.inf",
		"char\\tmABCD\\tmh-a12a.inf",
		"char\\tmABCD\\tmh-a13a.inf",
		"char\\tmABCD\\TmhA14t.inf" ,
		"char\\tmABCD\\TmhA15t.inf" ,
		"char\\tmABCD\\TmhA16t.inf" ,
		"char\\tmABCD\\TmhA17t.inf" ,
		"char\\tmABCD\\tmh-a19.inf" ,
		"char\\tmABCD\\tmh-a20.inf" ,
		"char\\tmABCD\\tmh-a21.inf" ,
		"char\\tmABCD\\tmh-a22.inf" ,
		"char\\tmABCD\\tmh-a23.inf" ,
		"char\\tmABCD\\Tmh-A24.inf",
		"char\\tmABCD\\Tmh-A25.inf",
		"char\\tmABCD\\Tmh-A26.inf",
		"char\\tmABCD\\hmech_02.inf",
		"char\\tmABCD\\hmech_03.inf",
		"char\\tmABCD\\CartolaMS.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\Tmh-A99.inf",
		"char\\tmABCD\\msxmas.inf",
		"char\\tmABCD\\CarnivalHatMS.inf",
		"char\\tmABCD\\Tmh-A27.inf"
	},
	{
		"char\\tmABCD\\tmh_a01b.inf",
		"char\\tmABCD\\tmh_a02b.inf",
		"char\\tmABCD\\tmh_a03b.inf",
		"char\\tmABCD\\tmh_a04b.inf",
		"char\\tmABCD\\tmh_a05b.inf",
		"char\\tmABCD\\tmh_a06b.inf",
		"char\\tmABCD\\tmh_a07b.inf",
		"char\\tmABCD\\tmh_a08b.inf",
		"char\\tmABCD\\tmh_a09b.inf",
		"char\\tmABCD\\tmh_a10b.inf",
		"char\\tmABCD\\tmh_a11b.inf",
		"char\\tmABCD\\tmh_a12b.inf",
		"char\\tmABCD\\tmh_a13b.inf",
		"char\\tmABCD\\TmhA14t.inf" ,
		"char\\tmABCD\\TmhA15t.inf" ,
		"char\\tmABCD\\TmhA16t.inf" ,
		"char\\tmABCD\\TmhA17t.inf" ,
		"char\\tmABCD\\tmh-a19.inf" ,
		"char\\tmABCD\\tmh-a20.inf" ,
		"char\\tmABCD\\tmh-a21.inf" ,
		"char\\tmABCD\\tmh-a22.inf" ,
		"char\\tmABCD\\tmh-a23.inf" ,
		"char\\tmABCD\\Tmh-A24.inf",
		"char\\tmABCD\\Tmh-A25.inf",
		"char\\tmABCD\\Tmh-A26.inf",
		"char\\tmABCD\\hmech_02.inf",
		"char\\tmABCD\\hmech_03.inf",
		"char\\tmABCD\\CartolaMS.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\Tmh-A99.inf",
		"char\\tmABCD\\msxmas.inf",
		"char\\tmABCD\\CarnivalHatMS.inf",
		"char\\tmABCD\\Tmh-A27.inf"
	},
	{
		"char\\tmABCD\\tmh-a01c.inf",
		"char\\tmABCD\\tmh-a02c.inf",
		"char\\tmABCD\\tmh-a03c.inf",
		"char\\tmABCD\\tmh-a04c.inf",
		"char\\tmABCD\\tmh-a05c.inf",
		"char\\tmABCD\\tmh-a06c.inf",
		"char\\tmABCD\\tmh-a07c.inf",
		"char\\tmABCD\\tmh-a08c.inf",
		"char\\tmABCD\\tmh-a09c.inf",
		"char\\tmABCD\\tmh-a10c.inf",
		"char\\tmABCD\\tmh-a11c.inf",
		"char\\tmABCD\\tmh-a12c.inf",
		"char\\tmABCD\\tmh-a13c.inf",
		"char\\tmABCD\\TmhA14t.inf" ,
		"char\\tmABCD\\TmhA15t.inf" ,
		"char\\tmABCD\\TmhA16t.inf" ,
		"char\\tmABCD\\TmhA17t.inf" ,
		"char\\tmABCD\\tmh-a19.inf" ,
		"char\\tmABCD\\tmh-a20.inf" ,
		"char\\tmABCD\\tmh-a21.inf" ,
		"char\\tmABCD\\tmh-a22.inf" ,
		"char\\tmABCD\\tmh-a23.inf" ,
		"char\\tmABCD\\Tmh-A24.inf",
		"char\\tmABCD\\Tmh-A25.inf",
		"char\\tmABCD\\Tmh-A26.inf",
		"char\\tmABCD\\hmech_02.inf",
		"char\\tmABCD\\hmech_03.inf",
		"char\\tmABCD\\CartolaMS.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\Tmh-A99.inf",
		"char\\tmABCD\\msxmas.inf",
		"char\\tmABCD\\CarnivalHatMS.inf",
		"char\\tmABCD\\Tmh-A27.inf"
	},
	{
		"char\\tmABCD\\tmh-a01d.inf",
		"char\\tmABCD\\tmh-a02d.inf",
		"char\\tmABCD\\tmh-a03d.inf",
		"char\\tmABCD\\tmh-a04d.inf",
		"char\\tmABCD\\tmh-a05d.inf",
		"char\\tmABCD\\tmh-a06d.inf",
		"char\\tmABCD\\tmh-a07d.inf",
		"char\\tmABCD\\tmh-a08d.inf",
		"char\\tmABCD\\tmh-a09d.inf",
		"char\\tmABCD\\tmh-a10d.inf",
		"char\\tmABCD\\tmh-a11d.inf",
		"char\\tmABCD\\tmh-a12d.inf",
		"char\\tmABCD\\tmh-a13d.inf",
		"char\\tmABCD\\TmhA14t.inf" ,
		"char\\tmABCD\\TmhA15t.inf" ,
		"char\\tmABCD\\TmhA16t.inf" ,
		"char\\tmABCD\\TmhA17t.inf" ,
		"char\\tmABCD\\tmh-a19.inf" ,
		"char\\tmABCD\\tmh-a20.inf" ,
		"char\\tmABCD\\tmh-a21.inf" ,
		"char\\tmABCD\\tmh-a22.inf" ,
		"char\\tmABCD\\tmh-a23.inf" ,
		"char\\tmABCD\\Tmh-A24.inf",
		"char\\tmABCD\\Tmh-A25.inf",
		"char\\tmABCD\\Tmh-A26.inf",
		"char\\tmABCD\\hmech_02.inf",
		"char\\tmABCD\\hmech_03.inf",
		"char\\tmABCD\\CartolaMS.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\Tmh-A99.inf",
		"char\\tmABCD\\msxmas.inf",
		"char\\tmABCD\\CarnivalHatMS.inf",
		"char\\tmABCD\\Tmh-A27.inf"
	},
	{
		"char\\tmABCD\\tmh-a01b.inf",
		"char\\tmABCD\\tmh-a02b.inf",
		"char\\tmABCD\\tmh-a03b.inf",
		"char\\tmABCD\\tmh-a01b.inf",
		"char\\tmABCD\\tmh-a02b.inf",
		"char\\tmABCD\\tmh-a03b.inf",
		"char\\tmABCD\\tmh-a01b.inf",
		"char\\tmABCD\\tmh-a02b.inf",
		"char\\tmABCD\\tmh-a03b.inf",
		"char\\tmABCD\\tmh-a01b.inf",
		"char\\tmABCD\\tmh-a02b.inf",
		"char\\tmABCD\\tmh-a03b.inf",
		"char\\tmABCD\\tmh-a01b.inf",
		"char\\tmABCD\\tmh-a02b.inf",
		"char\\tmABCD\\tmh-a03b.inf",
		"char\\tmABCD\\tmh-a01b.inf",
		"char\\tmABCD\\tmh-a02b.inf",
		"char\\tmABCD\\tmh-a03b.inf",
		"char\\tmABCD\\tmh-a01b.inf",
		"char\\tmABCD\\tmh-a02b.inf",
		"char\\tmABCD\\tmh-a03b.inf",
		"char\\tmABCD\\tmh-a01b.inf",
		"char\\tmABCD\\Tmh-A24.inf",
		"char\\tmABCD\\Tmh-A25.inf",
		"char\\tmABCD\\Tmh-A26.inf",
		"char\\tmABCD\\hmech_02.inf",
		"char\\tmABCD\\hmech_03.inf",
		"char\\tmABCD\\CartolaMS.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\Tmh-A99.inf",
		"char\\tmABCD\\msxmas.inf",
		"char\\tmABCD\\CarnivalHatMS.inf",
		"char\\tmABCD\\Tmh-A27.inf"
	},
	{
		"char\\tmABCD\\tmh-a01t.inf",
		"char\\tmABCD\\tmh-a02t.inf",
		"char\\tmABCD\\tmh-a03t.inf",
		"char\\tmABCD\\tmh-a01t.inf",
		"char\\tmABCD\\tmh-a02t.inf",
		"char\\tmABCD\\tmh-a03t.inf",
		"char\\tmABCD\\tmh-a01t.inf",
		"char\\tmABCD\\tmh-a02t.inf",
		"char\\tmABCD\\tmh-a01t.inf",
		"char\\tmABCD\\tmh-a02t.inf",
		"char\\tmABCD\\tmh-a03t.inf",
		"char\\tmABCD\\tmh-a01t.inf",
		"char\\tmABCD\\tmh-a02t.inf",
		"char\\tmABCD\\tmh-a03t.inf",
		"char\\tmABCD\\tmh-a01t.inf",
		"char\\tmABCD\\tmh-a02t.inf",
		"char\\tmABCD\\tmh-a03t.inf",
		"char\\tmABCD\\tmh-a01t.inf",
		"char\\tmABCD\\tmh-a02t.inf",
		"char\\tmABCD\\tmh-a03t.inf",
		"char\\tmABCD\\tmh-a01t.inf",
		"char\\tmABCD\\tmh-a02t.inf",
		"char\\tmABCD\\Tmh-A24.inf",
		"char\\tmABCD\\Tmh-A25.inf",
		"char\\tmABCD\\Tmh-A26.inf",
		"char\\tmABCD\\hmech_02.inf",
		"char\\tmABCD\\hmech_03.inf",
		"char\\tmABCD\\CartolaMS.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\Tmh-A99.inf",
		"char\\tmABCD\\msxmas.inf",
		"char\\tmABCD\\CarnivalHatMS.inf",
		"char\\tmABCD\\Tmh-A27.inf"
	},
	{
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\Tmh-A24.inf",
		"char\\tmABCD\\Tmh-A25.inf",
		"char\\tmABCD\\Tmh-A26.inf",
		"char\\tmABCD\\hmech_02.inf",
		"char\\tmABCD\\hmech_03.inf",
		"char\\tmABCD\\CartolaMS.inf",
		"char\\tmABCD\\TmhA-18t.inf",
		"char\\tmABCD\\Tmh-A99.inf",
		"char\\tmABCD\\msxmas.inf",
		"char\\tmABCD\\CarnivalHatMS.inf",
		"char\\tmABCD\\Tmh-A27.inf"
	}
};

char* szModel_ArcherFaceName[FACE_MODEL_MAX][HEAREPOTION_MAX] = {
	{
		"char\\tmABCD\\tfh-D01.inf",
		"char\\tmABCD\\tfh-d02.inf",
		"char\\tmABCD\\tfh-d03.inf",
		"char\\tmABCD\\tfh-d04.inf",
		"char\\tmABCD\\tfh-d05.inf",
		"char\\tmABCD\\tfh-d06.inf",
		"char\\tmABCD\\tfh-d07.inf",
		"char\\tmABCD\\tfh-d08.inf",
		"char\\tmABCD\\tfh-d09.inf",
		"char\\tmABCD\\tfh-d10.inf",
		"char\\tmABCD\\tfh-d11.inf",
		"char\\tmABCD\\tfh-d12.inf",
		"char\\tmABCD\\tfh-d13.inf",
		"char\\tmABCD\\TfhD14t.inf",
		"char\\tmABCD\\TfhD15t.inf",
		"char\\tmABCD\\TfhD16t.inf",
		"char\\tmABCD\\TfhD17t.inf",
		"char\\tmABCD\\tfh-d19.inf",
		"char\\tmABCD\\tfh-d20.inf",
		"char\\tmABCD\\tfh-d21.inf",
		"char\\tmABCD\\tfh-d22.inf",
		"char\\tmABCD\\tfh-d23.inf",
		"char\\tmABCD\\Tfh-D24.inf",
		"char\\tmABCD\\Tfh-D25.inf",
		"char\\tmABCD\\Tfh-D26.inf",
		"char\\tmABCD\\harcher_02.inf",
		"char\\tmABCD\\harcher_03.inf",
		"char\\tmABCD\\ar0nas.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\Tfh-D99.inf",
		"char\\tmABCD\\asxmas.inf",
		"char\\tmABCD\\CarnivalHatAS.inf",
		"char\\tmABCD\\Tfh-D27.inf"
	},
	{
		"char\\tmABCD\\tfh-D01a.inf",
		"char\\tmABCD\\tfh-d02a.inf",
		"char\\tmABCD\\tfh-d03a.inf",
		"char\\tmABCD\\tfh-d04a.inf",
		"char\\tmABCD\\tfh-d05a.inf",
		"char\\tmABCD\\tfh-d06a.inf",
		"char\\tmABCD\\tfh-d07a.inf",
		"char\\tmABCD\\tfh-d08a.inf",
		"char\\tmABCD\\tfh-d09a.inf",
		"char\\tmABCD\\tfh-d10a.inf",
		"char\\tmABCD\\tfh-d11a.inf",
		"char\\tmABCD\\tfh-d12a.inf",
		"char\\tmABCD\\tfh-d13a.inf",
		"char\\tmABCD\\TfhD14t.inf" ,
		"char\\tmABCD\\TfhD15t.inf" ,
		"char\\tmABCD\\TfhD16t.inf" ,
		"char\\tmABCD\\TfhD17t.inf" ,
		"char\\tmABCD\\tfh-d19.inf" ,
		"char\\tmABCD\\tfh-d20.inf" ,
		"char\\tmABCD\\tfh-d21.inf" ,
		"char\\tmABCD\\tfh-d22.inf" ,
		"char\\tmABCD\\tfh-d23.inf" ,
		"char\\tmABCD\\Tfh-D24.inf",
		"char\\tmABCD\\Tfh-D25.inf",
		"char\\tmABCD\\Tfh-D26.inf",
		"char\\tmABCD\\harcher_02.inf",
		"char\\tmABCD\\harcher_03.inf",
		"char\\tmABCD\\ar0nas.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\Tfh-D99.inf",
		"char\\tmABCD\\asxmas.inf",
		"char\\tmABCD\\CarnivalHatAS.inf",
		"char\\tmABCD\\Tfh-D27.inf"
	},
	{
		"char\\tmABCD\\tfh_D01b.inf",
		"char\\tmABCD\\tfh_d02b.inf",
		"char\\tmABCD\\tfh_d03b.inf",
		"char\\tmABCD\\tfh_d04b.inf",
		"char\\tmABCD\\tfh_d05b.inf",
		"char\\tmABCD\\tfh_d06b.inf",
		"char\\tmABCD\\tfh_d07b.inf",
		"char\\tmABCD\\tfh_d08b.inf",
		"char\\tmABCD\\tfh_d09b.inf",
		"char\\tmABCD\\tfh_d10b.inf",
		"char\\tmABCD\\tfh_d11b.inf",
		"char\\tmABCD\\tfh_d12b.inf",
		"char\\tmABCD\\tfh_d13b.inf",
		"char\\tmABCD\\TfhD14t.inf" ,
		"char\\tmABCD\\TfhD15t.inf" ,
		"char\\tmABCD\\TfhD16t.inf" ,
		"char\\tmABCD\\TfhD17t.inf" ,
		"char\\tmABCD\\tfh-d19.inf" ,
		"char\\tmABCD\\tfh-d20.inf" ,
		"char\\tmABCD\\tfh-d21.inf" ,
		"char\\tmABCD\\tfh-d22.inf" ,
		"char\\tmABCD\\tfh-d23.inf" ,
		"char\\tmABCD\\Tfh-D24.inf",
		"char\\tmABCD\\Tfh-D25.inf",
		"char\\tmABCD\\Tfh-D26.inf",
		"char\\tmABCD\\harcher_02.inf",
		"char\\tmABCD\\harcher_03.inf",
		"char\\tmABCD\\ar0nas.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\Tfh-D99.inf",
		"char\\tmABCD\\asxmas.inf",
		"char\\tmABCD\\CarnivalHatAS.inf",
		"char\\tmABCD\\Tfh-D27.inf"
	},
	{
		"char\\tmABCD\\tfh-D01c.inf",
		"char\\tmABCD\\tfh-d02c.inf",
		"char\\tmABCD\\tfh-d03c.inf",
		"char\\tmABCD\\tfh-d04c.inf",
		"char\\tmABCD\\tfh-d05c.inf",
		"char\\tmABCD\\tfh-d06c.inf",
		"char\\tmABCD\\tfh-d07c.inf",
		"char\\tmABCD\\tfh-d08c.inf",
		"char\\tmABCD\\tfh-d09c.inf",
		"char\\tmABCD\\tfh-d10c.inf",
		"char\\tmABCD\\tfh-d11c.inf",
		"char\\tmABCD\\tfh-d12c.inf",
		"char\\tmABCD\\tfh-d13c.inf",
		"char\\tmABCD\\TfhD14t.inf" ,
		"char\\tmABCD\\TfhD15t.inf" ,
		"char\\tmABCD\\TfhD16t.inf" ,
		"char\\tmABCD\\TfhD17t.inf" ,
		"char\\tmABCD\\tfh-d19.inf" ,
		"char\\tmABCD\\tfh-d20.inf" ,
		"char\\tmABCD\\tfh-d21.inf" ,
		"char\\tmABCD\\tfh-d22.inf" ,
		"char\\tmABCD\\tfh-d23.inf" ,
		"char\\tmABCD\\Tfh-D24.inf",
		"char\\tmABCD\\Tfh-D25.inf",
		"char\\tmABCD\\Tfh-D26.inf",
		"char\\tmABCD\\harcher_02.inf",
		"char\\tmABCD\\harcher_03.inf",
		"char\\tmABCD\\ar0nas.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\Tfh-D99.inf",
		"char\\tmABCD\\asxmas.inf",
		"char\\tmABCD\\CarnivalHatAS.inf",
		"char\\tmABCD\\Tfh-D27.inf"
	},
	{
		"char\\tmABCD\\tfh-D01d.inf",
		"char\\tmABCD\\tfh-d02d.inf",
		"char\\tmABCD\\tfh-d03d.inf",
		"char\\tmABCD\\tfh-d04d.inf",
		"char\\tmABCD\\tfh-d05d.inf",
		"char\\tmABCD\\tfh-d06d.inf",
		"char\\tmABCD\\tfh-d07d.inf",
		"char\\tmABCD\\tfh-d08d.inf",
		"char\\tmABCD\\tfh-d09d.inf",
		"char\\tmABCD\\tfh-d10d.inf",
		"char\\tmABCD\\tfh-d11d.inf",
		"char\\tmABCD\\tfh-d12d.inf",
		"char\\tmABCD\\tfh-d13d.inf",
		"char\\tmABCD\\TfhD14t.inf" ,
		"char\\tmABCD\\TfhD15t.inf" ,
		"char\\tmABCD\\TfhD16t.inf" ,
		"char\\tmABCD\\TfhD17t.inf" ,
		"char\\tmABCD\\tfh-d19.inf" ,
		"char\\tmABCD\\tfh-d20.inf" ,
		"char\\tmABCD\\tfh-d21.inf" ,
		"char\\tmABCD\\tfh-d22.inf" ,
		"char\\tmABCD\\tfh-d23.inf" ,
		"char\\tmABCD\\Tfh-D24.inf",
		"char\\tmABCD\\Tfh-D25.inf",
		"char\\tmABCD\\Tfh-D26.inf",
		"char\\tmABCD\\harcher_02.inf",
		"char\\tmABCD\\harcher_03.inf",
		"char\\tmABCD\\ar0nas.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\Tfh-D99.inf",
		"char\\tmABCD\\asxmas.inf",
		"char\\tmABCD\\CarnivalHatAS.inf",
		"char\\tmABCD\\Tfh-D27.inf"
	},
	{
		"char\\tmABCD\\tfh-D01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-d03t.inf",
		"char\\tmABCD\\tfh-D01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-d03t.inf",
		"char\\tmABCD\\tfh-D01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-D01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-d03t.inf",
		"char\\tmABCD\\tfh-D01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-d03t.inf",
		"char\\tmABCD\\tfh-d01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-d03t.inf",
		"char\\tmABCD\\tfh-d01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-d03t.inf",
		"char\\tmABCD\\tfh-d01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\Tfh-D24.inf",
		"char\\tmABCD\\Tfh-D25.inf",
		"char\\tmABCD\\Tfh-D26.inf",
		"char\\tmABCD\\harcher_02.inf",
		"char\\tmABCD\\harcher_03.inf",
		"char\\tmABCD\\ar0nas.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\Tfh-D99.inf",
		"char\\tmABCD\\asxmas.inf",
		"char\\tmABCD\\CarnivalHatAS.inf",
		"char\\tmABCD\\Tfh-D27.inf"
	},
	{
		"char\\tmABCD\\tfh-D01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-d03t.inf",
		"char\\tmABCD\\tfh-D01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-d03t.inf",
		"char\\tmABCD\\tfh-D01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-D01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-d03t.inf",
		"char\\tmABCD\\tfh-D01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-d03t.inf",
		"char\\tmABCD\\tfh-d01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-d03t.inf",
		"char\\tmABCD\\tfh-d01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\tfh-d03t.inf",
		"char\\tmABCD\\tfh-d01t.inf",
		"char\\tmABCD\\tfh-d02t.inf",
		"char\\tmABCD\\Tfh-D24.inf",
		"char\\tmABCD\\Tfh-D25.inf",
		"char\\tmABCD\\Tfh-D26.inf",
		"char\\tmABCD\\harcher_02.inf",
		"char\\tmABCD\\harcher_03.inf",
		"char\\tmABCD\\ar0nas.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\Tfh-D99.inf",
		"char\\tmABCD\\asxmas.inf",
		"char\\tmABCD\\CarnivalHatAS.inf",
		"char\\tmABCD\\Tfh-D27.inf"
	},
	{
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\Tfh-D24.inf",
		"char\\tmABCD\\Tfh-D25.inf",
		"char\\tmABCD\\Tfh-D26.inf",
		"char\\tmABCD\\harcher_02.inf",
		"char\\tmABCD\\harcher_03.inf",
		"char\\tmABCD\\ar0nas.inf",
		"char\\tmABCD\\TfhD-18t.inf",
		"char\\tmABCD\\Tfh-D99.inf",
		"char\\tmABCD\\asxmas.inf",
		"char\\tmABCD\\CarnivalHatAS.inf",
		"char\\tmABCD\\Tfh-D27.inf"
	}
};

char* szModel_PikeFaceName[FACE_MODEL_MAX][HEAREPOTION_MAX] = {
	{
		"char\\tmABCD\\tmh-c01.inf",
		"char\\tmABCD\\tmh-c02.inf",
		"char\\tmABCD\\tmh-c03.inf",
		"char\\tmABCD\\tmh-c04.inf",
		"char\\tmABCD\\tmh-c05.inf",
		"char\\tmABCD\\tmh-c06.inf",
		"char\\tmABCD\\tmh-c07.inf",
		"char\\tmABCD\\tmh-c08.inf",
		"char\\tmABCD\\tmh-c09.inf",
		"char\\tmABCD\\tmh-c10.inf",
		"char\\tmABCD\\tmh-c11.inf",
		"char\\tmABCD\\tmh-c12.inf",
		"char\\tmABCD\\tmh-c13.inf",
		"char\\tmABCD\\TmhC14t.inf",
		"char\\tmABCD\\TmhC15t.inf",
		"char\\tmABCD\\TmhC16t.inf",
		"char\\tmABCD\\TmhC17t.inf",
		"char\\tmABCD\\tmh-c19.inf",
		"char\\tmABCD\\tmh-c20.inf",
		"char\\tmABCD\\tmh-c21.inf",
		"char\\tmABCD\\tmh-c22.inf",
		"char\\tmABCD\\tmh-c23.inf",
		"char\\tmABCD\\Tmh-C24.inf",
		"char\\tmABCD\\Tmh-C25.inf",
		"char\\tmABCD\\Tmh-C26.inf",
		"char\\tmABCD\\hpike_02.inf",
		"char\\tmABCD\\hpike_03.inf",
		"char\\tmABCD\\CartolaPS.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\Tmh-C99.inf",
		"char\\tmABCD\\psxmas.inf",
		"char\\tmABCD\\CarnivalHatPS.inf",
		"char\\tmABCD\\Tmh-C27.inf"
	},
	{
		"char\\tmABCD\\tmh-c01a.inf",
		"char\\tmABCD\\tmh-c02a.inf",
		"char\\tmABCD\\tmh-c03a.inf",
		"char\\tmABCD\\tmh-c04a.inf",
		"char\\tmABCD\\tmh-c05a.inf",
		"char\\tmABCD\\tmh-c06a.inf",
		"char\\tmABCD\\tmh-c07a.inf",
		"char\\tmABCD\\tmh-c08a.inf",
		"char\\tmABCD\\tmh-c09a.inf",
		"char\\tmABCD\\tmh-c10a.inf",
		"char\\tmABCD\\tmh-c11a.inf",
		"char\\tmABCD\\tmh-c12a.inf",
		"char\\tmABCD\\tmh-c13a.inf",
		"char\\tmABCD\\TmhC14t.inf" ,
		"char\\tmABCD\\TmhC15t.inf" ,
		"char\\tmABCD\\TmhC16t.inf" ,
		"char\\tmABCD\\TmhC17t.inf" ,
		"char\\tmABCD\\tmh-c19.inf" ,
		"char\\tmABCD\\tmh-c20.inf" ,
		"char\\tmABCD\\tmh-c21.inf" ,
		"char\\tmABCD\\tmh-c22.inf" ,
		"char\\tmABCD\\tmh-c23.inf" ,
		"char\\tmABCD\\Tmh-C24.inf",
		"char\\tmABCD\\Tmh-C25.inf",
		"char\\tmABCD\\Tmh-C26.inf",
		"char\\tmABCD\\hpike_02.inf",
		"char\\tmABCD\\hpike_03.inf",
		"char\\tmABCD\\CartolaPS.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\Tmh-C99.inf",
		"char\\tmABCD\\psxmas.inf",
		"char\\tmABCD\\CarnivalHatPS.inf",
		"char\\tmABCD\\Tmh-C27.inf"
	},
	{
		"char\\tmABCD\\tmh_c01b.inf",
		"char\\tmABCD\\tmh_c02b.inf",
		"char\\tmABCD\\tmh_c03b.inf",
		"char\\tmABCD\\tmh_c04b.inf",
		"char\\tmABCD\\tmh_c05b.inf",
		"char\\tmABCD\\tmh_c06b.inf",
		"char\\tmABCD\\tmh_c07b.inf",
		"char\\tmABCD\\tmh_c08b.inf",
		"char\\tmABCD\\tmh_c09b.inf",
		"char\\tmABCD\\tmh_c10b.inf",
		"char\\tmABCD\\tmh_c11b.inf",
		"char\\tmABCD\\tmh_c12b.inf",
		"char\\tmABCD\\tmh_c13b.inf",
		"char\\tmABCD\\TmhC14t.inf" ,
		"char\\tmABCD\\TmhC15t.inf" ,
		"char\\tmABCD\\TmhC16t.inf" ,
		"char\\tmABCD\\TmhC17t.inf" ,
		"char\\tmABCD\\tmh-c19.inf" ,
		"char\\tmABCD\\tmh-c20.inf" ,
		"char\\tmABCD\\tmh-c21.inf" ,
		"char\\tmABCD\\tmh-c22.inf" ,
		"char\\tmABCD\\tmh-c23.inf" ,
		"char\\tmABCD\\Tmh-C24.inf",
		"char\\tmABCD\\Tmh-C25.inf",
		"char\\tmABCD\\Tmh-C26.inf",
		"char\\tmABCD\\hpike_02.inf",
		"char\\tmABCD\\hpike_03.inf",
		"char\\tmABCD\\CartolaPS.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\Tmh-C99.inf",
		"char\\tmABCD\\psxmas.inf",
		"char\\tmABCD\\CarnivalHatPS.inf",
		"char\\tmABCD\\Tmh-C27.inf"
	},
	{
		"char\\tmABCD\\tmhC-01c.inf",
		"char\\tmABCD\\tmhC-02c.inf",
		"char\\tmABCD\\tmhC-03c.inf",
		"char\\tmABCD\\tmhC-04c.inf",
		"char\\tmABCD\\tmhC-05c.inf",
		"char\\tmABCD\\tmhC-06c.inf",
		"char\\tmABCD\\tmhC-07c.inf",
		"char\\tmABCD\\tmhC-08c.inf",
		"char\\tmABCD\\tmhC-09c.inf",
		"char\\tmABCD\\tmhC-10c.inf",
		"char\\tmABCD\\tmhC-11c.inf",
		"char\\tmABCD\\tmhC-12c.inf",
		"char\\tmABCD\\tmhC-13c.inf",
		"char\\tmABCD\\TmhC14t.inf" ,
		"char\\tmABCD\\TmhC15t.inf" ,
		"char\\tmABCD\\TmhC16t.inf" ,
		"char\\tmABCD\\TmhC17t.inf" ,
		"char\\tmABCD\\tmh-c19.inf" ,
		"char\\tmABCD\\tmh-c20.inf" ,
		"char\\tmABCD\\tmh-c21.inf" ,
		"char\\tmABCD\\tmh-c22.inf" ,
		"char\\tmABCD\\tmh-c23.inf" ,
		"char\\tmABCD\\Tmh-C24.inf",
		"char\\tmABCD\\Tmh-C25.inf",
		"char\\tmABCD\\Tmh-C26.inf",
		"char\\tmABCD\\hpike_02.inf",
		"char\\tmABCD\\hpike_03.inf",
		"char\\tmABCD\\CartolaPS.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\Tmh-C99.inf",
		"char\\tmABCD\\psxmas.inf",
		"char\\tmABCD\\CarnivalHatPS.inf",
		"char\\tmABCD\\Tmh-C27.inf"
	},
	{
		"char\\tmABCD\\tmh-C01d.inf",
		"char\\tmABCD\\tmh-C02d.inf",
		"char\\tmABCD\\tmh-C03d.inf",
		"char\\tmABCD\\tmh-C04d.inf",
		"char\\tmABCD\\tmh-C05d.inf",
		"char\\tmABCD\\tmh-C06d.inf",
		"char\\tmABCD\\tmh-C07d.inf",
		"char\\tmABCD\\tmh-C08d.inf",
		"char\\tmABCD\\tmh-C09d.inf",
		"char\\tmABCD\\tmh-C10d.inf",
		"char\\tmABCD\\tmh-C11d.inf",
		"char\\tmABCD\\tmh-C12d.inf",
		"char\\tmABCD\\tmh-C13d.inf",
		"char\\tmABCD\\TmhC14t.inf" ,
		"char\\tmABCD\\TmhC15t.inf" ,
		"char\\tmABCD\\TmhC16t.inf" ,
		"char\\tmABCD\\TmhC17t.inf" ,
		"char\\tmABCD\\tmh-c19.inf" ,
		"char\\tmABCD\\tmh-c20.inf" ,
		"char\\tmABCD\\tmh-c21.inf" ,
		"char\\tmABCD\\tmh-c22.inf" ,
		"char\\tmABCD\\tmh-c23.inf" ,
		"char\\tmABCD\\Tmh-C24.inf",
		"char\\tmABCD\\Tmh-C25.inf",
		"char\\tmABCD\\Tmh-C26.inf",
		"char\\tmABCD\\hpike_02.inf",
		"char\\tmABCD\\hpike_03.inf",
		"char\\tmABCD\\CartolaPS.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\Tmh-C99.inf",
		"char\\tmABCD\\psxmas.inf",
		"char\\tmABCD\\CarnivalHatPS.inf",
		"char\\tmABCD\\Tmh-C27.inf"
	},
	{
		"char\\tmABCD\\tmh-c01b.inf",
		"char\\tmABCD\\tmh-c02b.inf",
		"char\\tmABCD\\tmh-c03b.inf",
		"char\\tmABCD\\tmh-c01b.inf",
		"char\\tmABCD\\tmh-c02b.inf",
		"char\\tmABCD\\tmh-c03b.inf",
		"char\\tmABCD\\tmh-c01b.inf",
		"char\\tmABCD\\tmh-c02b.inf",
		"char\\tmABCD\\tmh-c03b.inf",
		"char\\tmABCD\\tmh-c01b.inf",
		"char\\tmABCD\\tmh-c02b.inf",
		"char\\tmABCD\\tmh-c03b.inf",
		"char\\tmABCD\\tmh-c01b.inf",
		"char\\tmABCD\\tmh-c01b.inf",
		"char\\tmABCD\\tmh-c02b.inf",
		"char\\tmABCD\\tmh-c03b.inf",
		"char\\tmABCD\\tmh-c01b.inf",
		"char\\tmABCD\\tmh-c02b.inf",
		"char\\tmABCD\\tmh-c03b.inf",
		"char\\tmABCD\\tmh-c01b.inf",
		"char\\tmABCD\\tmh-c02b.inf",
		"char\\tmABCD\\tmh-c03b.inf",
		"char\\tmABCD\\Tmh-C24.inf",
		"char\\tmABCD\\Tmh-C25.inf",
		"char\\tmABCD\\Tmh-C26.inf",
		"char\\tmABCD\\hpike_02.inf",
		"char\\tmABCD\\hpike_03.inf",
		"char\\tmABCD\\CartolaPS.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\Tmh-C99.inf",
		"char\\tmABCD\\psxmas.inf",
		"char\\tmABCD\\CarnivalHatPS.inf",
		"char\\tmABCD\\Tmh-C27.inf"
	},
	{
		"char\\tmABCD\\tmh-c01t.inf",
		"char\\tmABCD\\tmh-c02t.inf",
		"char\\tmABCD\\tmh-c03t.inf",
		"char\\tmABCD\\tmh-c01t.inf",
		"char\\tmABCD\\tmh-c02t.inf",
		"char\\tmABCD\\tmh-c03t.inf",
		"char\\tmABCD\\tmh-c01t.inf",
		"char\\tmABCD\\tmh-c02t.inf",
		"char\\tmABCD\\tmh-c01t.inf",
		"char\\tmABCD\\tmh-c02t.inf",
		"char\\tmABCD\\tmh-c03t.inf",
		"char\\tmABCD\\tmh-c01t.inf",
		"char\\tmABCD\\tmh-c02t.inf",
		"char\\tmABCD\\tmh-c03t.inf",
		"char\\tmABCD\\tmh-c01t.inf",
		"char\\tmABCD\\tmh-c02t.inf",
		"char\\tmABCD\\tmh-c03t.inf",
		"char\\tmABCD\\tmh-c01t.inf",
		"char\\tmABCD\\tmh-c02t.inf",
		"char\\tmABCD\\tmh-c03t.inf",
		"char\\tmABCD\\tmh-c01t.inf",
		"char\\tmABCD\\tmh-c02t.inf",
		"char\\tmABCD\\Tmh-C24.inf",
		"char\\tmABCD\\Tmh-C25.inf",
		"char\\tmABCD\\Tmh-C26.inf",
		"char\\tmABCD\\hpike_02.inf",
		"char\\tmABCD\\hpike_03.inf",
		"char\\tmABCD\\CartolaPS.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\Tmh-C99.inf",
		"char\\tmABCD\\psxmas.inf",
		"char\\tmABCD\\CarnivalHatPS.inf",
		"char\\tmABCD\\Tmh-C27.inf"
	},
	{
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\Tmh-C24.inf",
		"char\\tmABCD\\Tmh-C25.inf",
		"char\\tmABCD\\Tmh-C26.inf",
		"char\\tmABCD\\hpike_02.inf",
		"char\\tmABCD\\hpike_03.inf",
		"char\\tmABCD\\CartolaPS.inf",
		"char\\tmABCD\\TmhC-18t.inf",
		"char\\tmABCD\\Tmh-C99.inf",
		"char\\tmABCD\\psxmas.inf",
		"char\\tmABCD\\CarnivalHatPS.inf",
		"char\\tmABCD\\Tmh-C27.inf"
	}
};

char* szModel_KnightFaceName[FACE_MODEL_MAX][HEAREPOTION_MAX] = {
	{
		"char\\tmABCD\\Mmh-A01.inf",
		"char\\tmABCD\\Mmh-A02.inf",
		"char\\tmABCD\\Mmh-A03.inf",
		"char\\tmABCD\\Mmh-A04.inf",
		"char\\tmABCD\\Mmh-A05.inf",
		"char\\tmABCD\\Mmh-A06.inf",
		"char\\tmABCD\\Mmh-A07.inf",
		"char\\tmABCD\\Mmh-A08.inf",
		"char\\tmABCD\\Mmh-A09.inf",
		"char\\tmABCD\\Mmh-A10.inf",
		"char\\tmABCD\\Mmh-A11.inf",
		"char\\tmABCD\\Mmh-A12.inf",
		"char\\tmABCD\\Mmh-A13.inf",
		"char\\tmABCD\\MmhA14t.inf",
		"char\\tmABCD\\MmhA15t.inf",
		"char\\tmABCD\\MmhA16t.inf",
		"char\\tmABCD\\MmhA17t.inf",
		"char\\tmABCD\\Mmh-A19.inf",
		"char\\tmABCD\\Mmh-A20.inf",
		"char\\tmABCD\\Mmh-A21.inf",
		"char\\tmABCD\\Mmh-A22.inf",
		"char\\tmABCD\\Mmh-A23.inf",
		"char\\tmABCD\\Mmh-A24.inf",
		"char\\tmABCD\\Mmh-A25.inf",
		"char\\tmABCD\\Mmh-A26.inf",
		"char\\tmABCD\\hknight_02.inf",
		"char\\tmABCD\\hknight_03.inf",
		"char\\tmABCD\\CartolaKS.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\Mmh-A99.inf",
		"char\\tmABCD\\ksxmas.inf",
		"char\\tmABCD\\CarnivalHatKS.inf",
		"char\\tmABCD\\Mmh-A27.inf"
	},
	{
		"char\\tmABCD\\Mmh-A01a.inf",
		"char\\tmABCD\\Mmh-A02a.inf",
		"char\\tmABCD\\Mmh-A03a.inf",
		"char\\tmABCD\\Mmh-A04a.inf",
		"char\\tmABCD\\Mmh-A05a.inf",
		"char\\tmABCD\\Mmh-A06a.inf",
		"char\\tmABCD\\Mmh-A07a.inf",
		"char\\tmABCD\\Mmh-A08a.inf",
		"char\\tmABCD\\Mmh-A09a.inf",
		"char\\tmABCD\\Mmh-A10a.inf",
		"char\\tmABCD\\Mmh-A11a.inf",
		"char\\tmABCD\\Mmh-A12a.inf",
		"char\\tmABCD\\Mmh-A13a.inf",
		"char\\tmABCD\\MmhA14t.inf"	,
		"char\\tmABCD\\MmhA15t.inf"	,
		"char\\tmABCD\\MmhA16t.inf"	,
		"char\\tmABCD\\MmhA17t.inf"	,
		"char\\tmABCD\\Mmh-A19.inf"	,
		"char\\tmABCD\\Mmh-A20.inf"	,
		"char\\tmABCD\\Mmh-A21.inf"	,
		"char\\tmABCD\\Mmh-A22.inf"	,
		"char\\tmABCD\\Mmh-A23.inf"	,
		"char\\tmABCD\\Mmh-A24.inf",
		"char\\tmABCD\\Mmh-A25.inf",
		"char\\tmABCD\\Mmh-A26.inf",
		"char\\tmABCD\\hknight_02.inf",
		"char\\tmABCD\\hknight_03.inf",
		"char\\tmABCD\\CartolaKS.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\Mmh-A99.inf",
		"char\\tmABCD\\ksxmas.inf",
		"char\\tmABCD\\CarnivalHatKS.inf",
		"char\\tmABCD\\Mmh-A27.inf"
	},
	{
		"char\\tmABCD\\Mmh_A01b.inf",
		"char\\tmABCD\\Mmh_A02b.inf",
		"char\\tmABCD\\Mmh_A03b.inf",
		"char\\tmABCD\\Mmh_A04b.inf",
		"char\\tmABCD\\Mmh_A05b.inf",
		"char\\tmABCD\\Mmh_A06b.inf",
		"char\\tmABCD\\Mmh_A07b.inf",
		"char\\tmABCD\\Mmh_A08b.inf",
		"char\\tmABCD\\Mmh_A09b.inf",
		"char\\tmABCD\\Mmh_A10b.inf",
		"char\\tmABCD\\Mmh_A11b.inf",
		"char\\tmABCD\\Mmh_A12b.inf",
		"char\\tmABCD\\Mmh_A13b.inf",
		"char\\tmABCD\\MmhA14t.inf"	,
		"char\\tmABCD\\MmhA15t.inf"	,
		"char\\tmABCD\\MmhA16t.inf"	,
		"char\\tmABCD\\MmhA17t.inf"	,
		"char\\tmABCD\\Mmh-A19.inf"	,
		"char\\tmABCD\\Mmh-A20.inf"	,
		"char\\tmABCD\\Mmh-A21.inf"	,
		"char\\tmABCD\\Mmh-A22.inf"	,
		"char\\tmABCD\\Mmh-A23.inf"	,
		"char\\tmABCD\\Mmh-A24.inf",
		"char\\tmABCD\\Mmh-A25.inf",
		"char\\tmABCD\\Mmh-A26.inf",
		"char\\tmABCD\\hknight_02.inf",
		"char\\tmABCD\\hknight_03.inf",
		"char\\tmABCD\\CartolaKS.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\Mmh-A99.inf",
		"char\\tmABCD\\ksxmas.inf",
		"char\\tmABCD\\CarnivalHatKS.inf",
		"char\\tmABCD\\Mmh-A27.inf"
	},
	{
		"char\\tmABCD\\Mmh-A01c.inf",
		"char\\tmABCD\\Mmh-A02c.inf",
		"char\\tmABCD\\Mmh-A03c.inf",
		"char\\tmABCD\\Mmh-A04c.inf",
		"char\\tmABCD\\Mmh-A05c.inf",
		"char\\tmABCD\\Mmh-A06c.inf",
		"char\\tmABCD\\Mmh-A07c.inf",
		"char\\tmABCD\\Mmh-A08c.inf",
		"char\\tmABCD\\Mmh-A09c.inf",
		"char\\tmABCD\\Mmh-A10c.inf",
		"char\\tmABCD\\Mmh-A11c.inf",
		"char\\tmABCD\\Mmh-A12c.inf",
		"char\\tmABCD\\Mmh-A13c.inf",
		"char\\tmABCD\\MmhA14t.inf"	,
		"char\\tmABCD\\MmhA15t.inf"	,
		"char\\tmABCD\\MmhA16t.inf"	,
		"char\\tmABCD\\MmhA17t.inf"	,
		"char\\tmABCD\\Mmh-A19.inf"	,
		"char\\tmABCD\\Mmh-A20.inf"	,
		"char\\tmABCD\\Mmh-A21.inf"	,
		"char\\tmABCD\\Mmh-A22.inf"	,
		"char\\tmABCD\\Mmh-A23.inf"	,
		"char\\tmABCD\\Mmh-A24.inf",
		"char\\tmABCD\\Mmh-A25.inf",
		"char\\tmABCD\\Mmh-A26.inf",
		"char\\tmABCD\\hknight_02.inf",
		"char\\tmABCD\\hknight_03.inf",
		"char\\tmABCD\\CartolaKS.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\Mmh-A99.inf",
		"char\\tmABCD\\ksxmas.inf",
		"char\\tmABCD\\CarnivalHatKS.inf",
		"char\\tmABCD\\Mmh-A27.inf"
	},
	{
		"char\\tmABCD\\Mmh-A01d.inf",
		"char\\tmABCD\\Mmh-A02d.inf",
		"char\\tmABCD\\Mmh-A03d.inf",
		"char\\tmABCD\\Mmh-A04d.inf",
		"char\\tmABCD\\Mmh-A05d.inf",
		"char\\tmABCD\\Mmh-A06d.inf",
		"char\\tmABCD\\Mmh-A07d.inf",
		"char\\tmABCD\\Mmh-A08d.inf",
		"char\\tmABCD\\Mmh-A09d.inf",
		"char\\tmABCD\\Mmh-A10d.inf",
		"char\\tmABCD\\Mmh-A11d.inf",
		"char\\tmABCD\\Mmh-A12d.inf",
		"char\\tmABCD\\Mmh-A13d.inf",
		"char\\tmABCD\\MmhA14t.inf"	,
		"char\\tmABCD\\MmhA15t.inf"	,
		"char\\tmABCD\\MmhA16t.inf"	,
		"char\\tmABCD\\MmhA17t.inf"	,
		"char\\tmABCD\\Mmh-A19.inf"	,
		"char\\tmABCD\\Mmh-A20.inf"	,
		"char\\tmABCD\\Mmh-A21.inf"	,
		"char\\tmABCD\\Mmh-A22.inf"	,
		"char\\tmABCD\\Mmh-A23.inf"	,
		"char\\tmABCD\\Mmh-A24.inf",
		"char\\tmABCD\\Mmh-A25.inf",
		"char\\tmABCD\\Mmh-A26.inf",
		"char\\tmABCD\\hknight_02.inf",
		"char\\tmABCD\\hknight_03.inf",
		"char\\tmABCD\\CartolaKS.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\Mmh-A99.inf",
		"char\\tmABCD\\ksxmas.inf",
		"char\\tmABCD\\CarnivalHatKS.inf",
		"char\\tmABCD\\Mmh-A27.inf"
	},
	{
		"char\\tmABCD\\Mmh-A01b.inf",
		"char\\tmABCD\\Mmh-A02b.inf",
		"char\\tmABCD\\Mmh-A03b.inf",
		"char\\tmABCD\\Mmh-A01b.inf",
		"char\\tmABCD\\Mmh-A02b.inf",
		"char\\tmABCD\\Mmh-A03b.inf",
		"char\\tmABCD\\Mmh-A01b.inf",
		"char\\tmABCD\\Mmh-A02b.inf",
		"char\\tmABCD\\Mmh-A03b.inf",
		"char\\tmABCD\\Mmh-A01b.inf",
		"char\\tmABCD\\Mmh-A02b.inf",
		"char\\tmABCD\\Mmh-A03b.inf",
		"char\\tmABCD\\Mmh-A01b.inf",
		"char\\tmABCD\\Mmh-A01b.inf",
		"char\\tmABCD\\Mmh-A02b.inf",
		"char\\tmABCD\\Mmh-A03b.inf",
		"char\\tmABCD\\Mmh-A01b.inf",
		"char\\tmABCD\\Mmh-A02b.inf",
		"char\\tmABCD\\Mmh-A03b.inf",
		"char\\tmABCD\\Mmh-A01b.inf",
		"char\\tmABCD\\Mmh-A02b.inf",
		"char\\tmABCD\\Mmh-A03b.inf",
		"char\\tmABCD\\Mmh-A24.inf",
		"char\\tmABCD\\Mmh-A25.inf",
		"char\\tmABCD\\Mmh-A26.inf",
		"char\\tmABCD\\hknight_02.inf",
		"char\\tmABCD\\hknight_03.inf",
		"char\\tmABCD\\CartolaKS.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\Mmh-A99.inf",
		"char\\tmABCD\\ksxmas.inf",
		"char\\tmABCD\\CarnivalHatKS.inf",
		"char\\tmABCD\\Mmh-A27.inf"
	},
	{
		"char\\tmABCD\\Mmh-A01t.inf",
		"char\\tmABCD\\Mmh-A02t.inf",
		"char\\tmABCD\\Mmh-A03t.inf",
		"char\\tmABCD\\Mmh-A01t.inf",
		"char\\tmABCD\\Mmh-A02t.inf",
		"char\\tmABCD\\Mmh-A03t.inf",
		"char\\tmABCD\\Mmh-A01t.inf",
		"char\\tmABCD\\Mmh-A02t.inf",
		"char\\tmABCD\\Mmh-A01t.inf",
		"char\\tmABCD\\Mmh-A02t.inf",
		"char\\tmABCD\\Mmh-A03t.inf",
		"char\\tmABCD\\Mmh-A01t.inf",
		"char\\tmABCD\\Mmh-A02t.inf",
		"char\\tmABCD\\Mmh-A03t.inf",
		"char\\tmABCD\\Mmh-A01t.inf",
		"char\\tmABCD\\Mmh-A02t.inf",
		"char\\tmABCD\\Mmh-A03t.inf",
		"char\\tmABCD\\Mmh-A01t.inf",
		"char\\tmABCD\\Mmh-A02t.inf",
		"char\\tmABCD\\Mmh-A03t.inf",
		"char\\tmABCD\\Mmh-A01t.inf",
		"char\\tmABCD\\Mmh-A02t.inf",
		"char\\tmABCD\\Mmh-A24.inf",
		"char\\tmABCD\\Mmh-A25.inf",
		"char\\tmABCD\\Mmh-A26.inf",
		"char\\tmABCD\\hknight_02.inf",
		"char\\tmABCD\\hknight_03.inf",
		"char\\tmABCD\\CartolaKS.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\Mmh-A99.inf",
		"char\\tmABCD\\ksxmas.inf",
		"char\\tmABCD\\CarnivalHatKS.inf",
		"char\\tmABCD\\Mmh-A27.inf"
	},
	{
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\Mmh-A24.inf",
		"char\\tmABCD\\Mmh-A25.inf",
		"char\\tmABCD\\Mmh-A26.inf",
		"char\\tmABCD\\hknight_02.inf",
		"char\\tmABCD\\hknight_03.inf",
		"char\\tmABCD\\CartolaKS.inf",
		"char\\tmABCD\\MmhA-18t.inf",
		"char\\tmABCD\\Mmh-A99.inf",
		"char\\tmABCD\\ksxmas.inf",
		"char\\tmABCD\\CarnivalHatKS.inf",
		"char\\tmABCD\\Mmh-A27.inf"
	}
};

char* szModel_AtalantaFaceName[FACE_MODEL_MAX][HEAREPOTION_MAX] = {
	{
		"char\\tmABCD\\Mfh-B01.inf",
		"char\\tmABCD\\Mfh-B02.inf",
		"char\\tmABCD\\Mfh-B03.inf",
		"char\\tmABCD\\Mfh-B04.inf",
		"char\\tmABCD\\Mfh-B05.inf",
		"char\\tmABCD\\Mfh-B06.inf",
		"char\\tmABCD\\Mfh-B07.inf",
		"char\\tmABCD\\Mfh-B08.inf",
		"char\\tmABCD\\Mfh-B09.inf",
		"char\\tmABCD\\Mfh-B10.inf",
		"char\\tmABCD\\Mfh-B11.inf",
		"char\\tmABCD\\Mfh-B12.inf",
		"char\\tmABCD\\Mfh-B13.inf",
		"char\\tmABCD\\MfhB14t.inf",
		"char\\tmABCD\\MfhB15t.inf",
		"char\\tmABCD\\MfhB16t.inf",
		"char\\tmABCD\\MfhB17t.inf",
		"char\\tmABCD\\Mfh-B19.inf",
		"char\\tmABCD\\Mfh-B20.inf",
		"char\\tmABCD\\Mfh-B21.inf",
		"char\\tmABCD\\Mfh-B22.inf",
		"char\\tmABCD\\Mfh-B23.inf",
		"char\\tmABCD\\Mfh-B24.inf",
		"char\\tmABCD\\Mfh-B25.inf",
		"char\\tmABCD\\Mfh-B26.inf",
		"char\\tmABCD\\hatalanta_02.inf",
		"char\\tmABCD\\hatalanta_03.inf",
		"char\\tmABCD\\ar0nATA.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\Mfh-B99.inf",
		"char\\tmABCD\\ataxmas.inf",
		"char\\tmABCD\\CarnivalHatATA.inf",
		"char\\tmABCD\\Mfh-B26.inf"
	},
	{
		"char\\tmABCD\\Mfh-B01a.inf",
		"char\\tmABCD\\Mfh-B02a.inf",
		"char\\tmABCD\\Mfh-B03a.inf",
		"char\\tmABCD\\Mfh-B04a.inf",
		"char\\tmABCD\\Mfh-B05a.inf",
		"char\\tmABCD\\Mfh-B06a.inf",
		"char\\tmABCD\\Mfh-B07a.inf",
		"char\\tmABCD\\Mfh-B08a.inf",
		"char\\tmABCD\\Mfh-B09a.inf",
		"char\\tmABCD\\Mfh-B10a.inf",
		"char\\tmABCD\\Mfh-B11a.inf",
		"char\\tmABCD\\Mfh-B12a.inf",
		"char\\tmABCD\\Mfh-B13a.inf",
		"char\\tmABCD\\MfhB14t.inf" ,
		"char\\tmABCD\\MfhB15t.inf" ,
		"char\\tmABCD\\MfhB16t.inf" ,
		"char\\tmABCD\\MfhB17t.inf" ,
		"char\\tmABCD\\Mfh-B19.inf" ,
		"char\\tmABCD\\Mfh-B20.inf" ,
		"char\\tmABCD\\Mfh-B21.inf" ,
		"char\\tmABCD\\Mfh-B22.inf" ,
		"char\\tmABCD\\Mfh-B23.inf" ,
		"char\\tmABCD\\Mfh-B24.inf",
		"char\\tmABCD\\Mfh-B25.inf",
		"char\\tmABCD\\Mfh-B26.inf",
		"char\\tmABCD\\hatalanta_02.inf",
		"char\\tmABCD\\hatalanta_03.inf",
		"char\\tmABCD\\ar0nATA.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\Mfh-B99.inf",
		"char\\tmABCD\\ataxmas.inf",
		"char\\tmABCD\\CarnivalHatATA.inf",
		"char\\tmABCD\\Mfh-B26.inf"
	},
	{
		"char\\tmABCD\\Mfh_B01b.inf",
		"char\\tmABCD\\Mfh_B02b.inf",
		"char\\tmABCD\\Mfh_B03b.inf",
		"char\\tmABCD\\Mfh_B04b.inf",
		"char\\tmABCD\\Mfh_B05b.inf",
		"char\\tmABCD\\Mfh_B06b.inf",
		"char\\tmABCD\\Mfh_B07b.inf",
		"char\\tmABCD\\Mfh_B08b.inf",
		"char\\tmABCD\\Mfh_B09b.inf",
		"char\\tmABCD\\Mfh_B10b.inf",
		"char\\tmABCD\\Mfh_B11b.inf",
		"char\\tmABCD\\Mfh_B12b.inf",
		"char\\tmABCD\\Mfh_B13b.inf",
		"char\\tmABCD\\MfhB14t.inf" ,
		"char\\tmABCD\\MfhB15t.inf" ,
		"char\\tmABCD\\MfhB16t.inf" ,
		"char\\tmABCD\\MfhB17t.inf" ,
		"char\\tmABCD\\Mfh-B19.inf" ,
		"char\\tmABCD\\Mfh-B20.inf" ,
		"char\\tmABCD\\Mfh-B21.inf" ,
		"char\\tmABCD\\Mfh-B22.inf" ,
		"char\\tmABCD\\Mfh-B23.inf" ,
		"char\\tmABCD\\Mfh-B24.inf",
		"char\\tmABCD\\Mfh-B25.inf",
		"char\\tmABCD\\Mfh-B26.inf",
		"char\\tmABCD\\hatalanta_02.inf",
		"char\\tmABCD\\hatalanta_03.inf",
		"char\\tmABCD\\ar0nATA.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\Mfh-B99.inf",
		"char\\tmABCD\\ataxmas.inf",
		"char\\tmABCD\\CarnivalHatATA.inf",
		"char\\tmABCD\\Mfh-B26.inf"
	},
	{
		"char\\tmABCD\\Mfh-B01c.inf",
		"char\\tmABCD\\Mfh-B02c.inf",
		"char\\tmABCD\\Mfh-B03c.inf",
		"char\\tmABCD\\Mfh-B04c.inf",
		"char\\tmABCD\\Mfh-B05c.inf",
		"char\\tmABCD\\Mfh-B06c.inf",
		"char\\tmABCD\\Mfh-B07c.inf",
		"char\\tmABCD\\Mfh-B08c.inf",
		"char\\tmABCD\\Mfh-B09c.inf",
		"char\\tmABCD\\Mfh-B10c.inf",
		"char\\tmABCD\\Mfh-B11c.inf",
		"char\\tmABCD\\Mfh-B12c.inf",
		"char\\tmABCD\\Mfh-B13c.inf",
		"char\\tmABCD\\MfhB14t.inf" ,
		"char\\tmABCD\\MfhB15t.inf" ,
		"char\\tmABCD\\MfhB16t.inf" ,
		"char\\tmABCD\\MfhB17t.inf" ,
		"char\\tmABCD\\Mfh-B19.inf" ,
		"char\\tmABCD\\Mfh-B20.inf" ,
		"char\\tmABCD\\Mfh-B21.inf" ,
		"char\\tmABCD\\Mfh-B22.inf" ,
		"char\\tmABCD\\Mfh-B23.inf" ,
		"char\\tmABCD\\Mfh-B24.inf",
		"char\\tmABCD\\Mfh-B25.inf",
		"char\\tmABCD\\Mfh-B26.inf",
		"char\\tmABCD\\hatalanta_02.inf",
		"char\\tmABCD\\hatalanta_03.inf",
		"char\\tmABCD\\ar0nATA.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\Mfh-B99.inf",
		"char\\tmABCD\\ataxmas.inf",
		"char\\tmABCD\\CarnivalHatATA.inf",
		"char\\tmABCD\\Mfh-B26.inf"
	},
	{
		"char\\tmABCD\\Mfh-B01d.inf",
		"char\\tmABCD\\Mfh-B02d.inf",
		"char\\tmABCD\\Mfh-B03d.inf",
		"char\\tmABCD\\Mfh-B04d.inf",
		"char\\tmABCD\\Mfh-B05d.inf",
		"char\\tmABCD\\Mfh-B06d.inf",
		"char\\tmABCD\\Mfh-B07d.inf",
		"char\\tmABCD\\Mfh-B08d.inf",
		"char\\tmABCD\\Mfh-B09d.inf",
		"char\\tmABCD\\Mfh-B10d.inf",
		"char\\tmABCD\\Mfh-B11d.inf",
		"char\\tmABCD\\Mfh-B12d.inf",
		"char\\tmABCD\\Mfh-B13d.inf",
		"char\\tmABCD\\MfhB14t.inf" ,
		"char\\tmABCD\\MfhB15t.inf" ,
		"char\\tmABCD\\MfhB16t.inf" ,
		"char\\tmABCD\\MfhB17t.inf" ,
		"char\\tmABCD\\Mfh-B19.inf" ,
		"char\\tmABCD\\Mfh-B20.inf" ,
		"char\\tmABCD\\Mfh-B21.inf" ,
		"char\\tmABCD\\Mfh-B22.inf" ,
		"char\\tmABCD\\Mfh-B23.inf" ,
		"char\\tmABCD\\Mfh-B24.inf",
		"char\\tmABCD\\Mfh-B25.inf",
		"char\\tmABCD\\Mfh-B26.inf",
		"char\\tmABCD\\hatalanta_02.inf",
		"char\\tmABCD\\hatalanta_03.inf",
		"char\\tmABCD\\ar0nATA.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\Mfh-B99.inf",
		"char\\tmABCD\\ataxmas.inf",
		"char\\tmABCD\\CarnivalHatATA.inf",
		"char\\tmABCD\\Mfh-B26.inf"
	},
	{
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B03t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B03t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B03t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B03t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B03t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B03t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B24.inf",
		"char\\tmABCD\\Mfh-B25.inf",
		"char\\tmABCD\\Mfh-B26.inf",
		"char\\tmABCD\\hatalanta_02.inf",
		"char\\tmABCD\\hatalanta_03.inf",
		"char\\tmABCD\\ar0nATA.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\Mfh-B99.inf",
		"char\\tmABCD\\ataxmas.inf",
		"char\\tmABCD\\CarnivalHatATA.inf",
		"char\\tmABCD\\Mfh-B26.inf"
	},
	{
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B03t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B03t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B03t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B03t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B03t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B03t.inf",
		"char\\tmABCD\\Mfh-B01t.inf",
		"char\\tmABCD\\Mfh-B02t.inf",
		"char\\tmABCD\\Mfh-B24.inf",
		"char\\tmABCD\\Mfh-B25.inf",
		"char\\tmABCD\\Mfh-B26.inf",
		"char\\tmABCD\\hatalanta_02.inf",
		"char\\tmABCD\\hatalanta_03.inf",
		"char\\tmABCD\\ar0nATA.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\Mfh-B99.inf",
		"char\\tmABCD\\ataxmas.inf",
		"char\\tmABCD\\CarnivalHatATA.inf",
		"char\\tmABCD\\Mfh-B26.inf"
	},
	{
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\Mfh-B24.inf",
		"char\\tmABCD\\Mfh-B25.inf",
		"char\\tmABCD\\Mfh-B26.inf",
		"char\\tmABCD\\hatalanta_02.inf",
		"char\\tmABCD\\hatalanta_03.inf",
		"char\\tmABCD\\ar0nATA.inf",
		"char\\tmABCD\\MfhB-18t.inf",
		"char\\tmABCD\\Mfh-B99.inf",
		"char\\tmABCD\\ataxmas.inf",
		"char\\tmABCD\\CarnivalHatATA.inf",
		"char\\tmABCD\\Mfh-B26.inf"
	}
};

char* szModel_PristessFaceName[FACE_MODEL_MAX][HEAREPOTION_MAX] = {
	{
		"char\\tmABCD\\Mfh-C01.inf",
		"char\\tmABCD\\Mfh-C02.inf",
		"char\\tmABCD\\Mfh-C03.inf",
		"char\\tmABCD\\Mfh-C04.inf",
		"char\\tmABCD\\Mfh-C05.inf",
		"char\\tmABCD\\Mfh-C06.inf",
		"char\\tmABCD\\Mfh-C07.inf",
		"char\\tmABCD\\Mfh-C08.inf",
		"char\\tmABCD\\Mfh-C09.inf",
		"char\\tmABCD\\Mfh-C10.inf",
		"char\\tmABCD\\Mfh-C11.inf",
		"char\\tmABCD\\Mfh-C12.inf",
		"char\\tmABCD\\Mfh-C13.inf",
		"char\\tmABCD\\MfhC14t.inf",
		"char\\tmABCD\\MfhC15t.inf",
		"char\\tmABCD\\MfhC16t.inf",
		"char\\tmABCD\\MfhC17t.inf",
		"char\\tmABCD\\Mfh-C19.inf",
		"char\\tmABCD\\Mfh-C20.inf",
		"char\\tmABCD\\Mfh-C21.inf",
		"char\\tmABCD\\Mfh-C22.inf",
		"char\\tmABCD\\Mfh-C23.inf",
		"char\\tmABCD\\Mfh-C24.inf",
		"char\\tmABCD\\Mfh-C25.inf",
		"char\\tmABCD\\Mfh-C26.inf",
		"char\\tmABCD\\hpriestess_02.inf",
		"char\\tmABCD\\hpriestess_03.inf",
		"char\\tmABCD\\ar0nPRS.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\Mfh-C99.inf",
		"char\\tmABCD\\prsxmas.inf",
		"char\\tmABCD\\CarnivalHatPRS.inf",
		"char\\tmABCD\\Mfh-C27.inf"
	},
	{
		"char\\tmABCD\\Mfh-C01a.inf",
		"char\\tmABCD\\Mfh-C02a.inf",
		"char\\tmABCD\\Mfh-C03a.inf",
		"char\\tmABCD\\Mfh-C04a.inf",
		"char\\tmABCD\\Mfh-C05a.inf",
		"char\\tmABCD\\Mfh-C06a.inf",
		"char\\tmABCD\\Mfh-C07a.inf",
		"char\\tmABCD\\Mfh-C08a.inf",
		"char\\tmABCD\\Mfh-C09a.inf",
		"char\\tmABCD\\Mfh-C10a.inf",
		"char\\tmABCD\\Mfh-C11a.inf",
		"char\\tmABCD\\Mfh-C12a.inf",
		"char\\tmABCD\\Mfh-C13a.inf",
		"char\\tmABCD\\MfhC14t.inf" ,
		"char\\tmABCD\\MfhC15t.inf" ,
		"char\\tmABCD\\MfhC16t.inf" ,
		"char\\tmABCD\\MfhC17t.inf" ,
		"char\\tmABCD\\Mfh-C19.inf" ,
		"char\\tmABCD\\Mfh-C20.inf" ,
		"char\\tmABCD\\Mfh-C21.inf" ,
		"char\\tmABCD\\Mfh-C22.inf" ,
		"char\\tmABCD\\Mfh-C23.inf" ,
		"char\\tmABCD\\Mfh-C24.inf",
		"char\\tmABCD\\Mfh-C25.inf",
		"char\\tmABCD\\Mfh-C26.inf",
		"char\\tmABCD\\hpriestess_02.inf",
		"char\\tmABCD\\hpriestess_03.inf",
		"char\\tmABCD\\ar0nPRS.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\Mfh-C99.inf",
		"char\\tmABCD\\prsxmas.inf",
		"char\\tmABCD\\CarnivalHatPRS.inf",
		"char\\tmABCD\\Mfh-C27.inf"
	},
	{
		"char\\tmABCD\\Mfh_C01b.inf",
		"char\\tmABCD\\Mfh_C02b.inf",
		"char\\tmABCD\\Mfh_C03b.inf",
		"char\\tmABCD\\Mfh_C04b.inf",
		"char\\tmABCD\\Mfh_C05b.inf",
		"char\\tmABCD\\Mfh_C06b.inf",
		"char\\tmABCD\\Mfh_C07b.inf",
		"char\\tmABCD\\Mfh_C08b.inf",
		"char\\tmABCD\\Mfh_C09b.inf",
		"char\\tmABCD\\Mfh_C10b.inf",
		"char\\tmABCD\\Mfh_C11b.inf",
		"char\\tmABCD\\Mfh_C12b.inf",
		"char\\tmABCD\\Mfh_C13b.inf",
		"char\\tmABCD\\MfhC14t.inf" ,
		"char\\tmABCD\\MfhC15t.inf" ,
		"char\\tmABCD\\MfhC16t.inf" ,
		"char\\tmABCD\\MfhC17t.inf" ,
		"char\\tmABCD\\Mfh-C19.inf" ,
		"char\\tmABCD\\Mfh-C20.inf" ,
		"char\\tmABCD\\Mfh-C21.inf" ,
		"char\\tmABCD\\Mfh-C22.inf" ,
		"char\\tmABCD\\Mfh-C23.inf" ,
		"char\\tmABCD\\Mfh-C24.inf",
		"char\\tmABCD\\Mfh-C25.inf",
		"char\\tmABCD\\Mfh-C26.inf",
		"char\\tmABCD\\hpriestess_02.inf",
		"char\\tmABCD\\hpriestess_03.inf",
		"char\\tmABCD\\ar0nPRS.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\Mfh-C99.inf",
		"char\\tmABCD\\prsxmas.inf",
		"char\\tmABCD\\CarnivalHatPRS.inf",
		"char\\tmABCD\\Mfh-C27.inf"
	},
	{
		"char\\tmABCD\\Mfh-C01c.inf",
		"char\\tmABCD\\Mfh-C02c.inf",
		"char\\tmABCD\\Mfh-C03c.inf",
		"char\\tmABCD\\Mfh-C04c.inf",
		"char\\tmABCD\\Mfh-C05c.inf",
		"char\\tmABCD\\Mfh-C06c.inf",
		"char\\tmABCD\\Mfh-C07c.inf",
		"char\\tmABCD\\Mfh-C08c.inf",
		"char\\tmABCD\\Mfh-C09c.inf",
		"char\\tmABCD\\Mfh-C10c.inf",
		"char\\tmABCD\\Mfh-C11c.inf",
		"char\\tmABCD\\Mfh-C12c.inf",
		"char\\tmABCD\\Mfh-C13c.inf",
		"char\\tmABCD\\MfhC14t.inf" ,
		"char\\tmABCD\\MfhC15t.inf" ,
		"char\\tmABCD\\MfhC16t.inf" ,
		"char\\tmABCD\\MfhC17t.inf" ,
		"char\\tmABCD\\Mfh-C19.inf" ,
		"char\\tmABCD\\Mfh-C20.inf" ,
		"char\\tmABCD\\Mfh-C21.inf" ,
		"char\\tmABCD\\Mfh-C22.inf" ,
		"char\\tmABCD\\Mfh-C23.inf" ,
		"char\\tmABCD\\Mfh-C24.inf",
		"char\\tmABCD\\Mfh-C25.inf",
		"char\\tmABCD\\Mfh-C26.inf",
		"char\\tmABCD\\hpriestess_02.inf",
		"char\\tmABCD\\hpriestess_03.inf",
		"char\\tmABCD\\ar0nPRS.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\Mfh-C99.inf",
		"char\\tmABCD\\prsxmas.inf",
		"char\\tmABCD\\CarnivalHatPRS.inf",
		"char\\tmABCD\\Mfh-C27.inf"
	},
	{
		"char\\tmABCD\\Mfh-C01d.inf" ,
		"char\\tmABCD\\Mfh-C02d.inf" ,
		"char\\tmABCD\\Mfh-C03d.inf" ,
		"char\\tmABCD\\Mfh-C04d.inf" ,
		"char\\tmABCD\\Mfh-C05d.inf" ,
		"char\\tmABCD\\Mfh-C006d.inf",
		"char\\tmABCD\\Mfh-C007d.inf",
		"char\\tmABCD\\Mfh-C008d.inf",
		"char\\tmABCD\\Mfh-C009d.inf",
		"char\\tmABCD\\Mfh-C10d.inf" ,
		"char\\tmABCD\\Mfh-C11d.inf" ,
		"char\\tmABCD\\Mfh-C12d.inf" ,
		"char\\tmABCD\\Mfh-C13d.inf" ,
		"char\\tmABCD\\MfhC14t.inf"  ,
		"char\\tmABCD\\MfhC15t.inf"  ,
		"char\\tmABCD\\MfhC16t.inf"  ,
		"char\\tmABCD\\MfhC17t.inf"  ,
		"char\\tmABCD\\Mfh-C19.inf"  ,
		"char\\tmABCD\\Mfh-C20.inf"  ,
		"char\\tmABCD\\Mfh-C21.inf"  ,
		"char\\tmABCD\\Mfh-C22.inf"  ,
		"char\\tmABCD\\Mfh-C23.inf"  ,
		"char\\tmABCD\\Mfh-C24.inf",
		"char\\tmABCD\\Mfh-C25.inf",
		"char\\tmABCD\\Mfh-C26.inf",
		"char\\tmABCD\\hpriestess_02.inf",
		"char\\tmABCD\\hpriestess_03.inf",
		"char\\tmABCD\\ar0nPRS.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\Mfh-C99.inf",
		"char\\tmABCD\\prsxmas.inf",
		"char\\tmABCD\\CarnivalHatPRS.inf",
		"char\\tmABCD\\Mfh-C27.inf"
	},
	{
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C03t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C03t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C03t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C03t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C03t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C03t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C24.inf",
		"char\\tmABCD\\Mfh-C25.inf",
		"char\\tmABCD\\Mfh-C26.inf",
		"char\\tmABCD\\hpriestess_02.inf",
		"char\\tmABCD\\hpriestess_03.inf",
		"char\\tmABCD\\ar0nPRS.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\Mfh-C99.inf",
		"char\\tmABCD\\prsxmas.inf",
		"char\\tmABCD\\CarnivalHatPRS.inf",
		"char\\tmABCD\\Mfh-C27.inf"
	},
	{
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C03t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C03t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C03t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C03t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C03t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C03t.inf",
		"char\\tmABCD\\Mfh-C01t.inf",
		"char\\tmABCD\\Mfh-C02t.inf",
		"char\\tmABCD\\Mfh-C24.inf",
		"char\\tmABCD\\Mfh-C25.inf",
		"char\\tmABCD\\Mfh-C26.inf",
		"char\\tmABCD\\hpriestess_02.inf",
		"char\\tmABCD\\hpriestess_03.inf",
		"char\\tmABCD\\ar0nPRS.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\Mfh-C99.inf",
		"char\\tmABCD\\prsxmas.inf",
		"char\\tmABCD\\CarnivalHatPRS.inf",
		"char\\tmABCD\\Mfh-C27.inf"
	},
	{
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\Mfh-C24.inf",
		"char\\tmABCD\\Mfh-C25.inf",
		"char\\tmABCD\\Mfh-C26.inf",
		"char\\tmABCD\\hpriestess_02.inf",
		"char\\tmABCD\\hpriestess_03.inf",
		"char\\tmABCD\\ar0nPRS.inf",
		"char\\tmABCD\\MfhC-18t.inf",
		"char\\tmABCD\\Mfh-C99.inf",
		"char\\tmABCD\\prsxmas.inf",
		"char\\tmABCD\\CarnivalHatPRS.inf",
		"char\\tmABCD\\Mfh-C27.inf"
	}
};

char* szModel_MagicanFaceName[FACE_MODEL_MAX][HEAREPOTION_MAX] = {
	{
		"char\\tmABCD\\Mmh-D01.inf",
		"char\\tmABCD\\Mmh-D02.inf",
		"char\\tmABCD\\Mmh-D03.inf",
		"char\\tmABCD\\Mmh-D04.inf",
		"char\\tmABCD\\Mmh-D05.inf",
		"char\\tmABCD\\Mmh-D06.inf",
		"char\\tmABCD\\Mmh-D07.inf",
		"char\\tmABCD\\Mmh-D08.inf",
		"char\\tmABCD\\Mmh-D09.inf",
		"char\\tmABCD\\Mmh-D10.inf",
		"char\\tmABCD\\Mmh-D11.inf",
		"char\\tmABCD\\Mmh-D12.inf",
		"char\\tmABCD\\Mmh-D13.inf",
		"char\\tmABCD\\MmhD14t.inf",
		"char\\tmABCD\\MmhD15t.inf",
		"char\\tmABCD\\MmhD16t.inf",
		"char\\tmABCD\\MmhD17t.inf",
		"char\\tmABCD\\Mmh-D19.inf",
		"char\\tmABCD\\Mmh-D20.inf",
		"char\\tmABCD\\Mmh-D21.inf",
		"char\\tmABCD\\Mmh-D22.inf",
		"char\\tmABCD\\Mmh-D23.inf",
		"char\\tmABCD\\Mmh-D24.inf",
		"char\\tmABCD\\Mmh-D25.inf",
		"char\\tmABCD\\Mmh-D26.inf",
		"char\\tmABCD\\hmage_02.inf",
		"char\\tmABCD\\hmage_03.inf",
		"char\\tmABCD\\CartolaMG.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\Mmh-D99.inf",
		"char\\tmABCD\\mgxmas.inf",
		"char\\tmABCD\\CarnivalHatMG.inf",
		"char\\tmABCD\\Mmh-D26.inf"
	},
	{
		"char\\tmABCD\\Mmh-D01a.inf",
		"char\\tmABCD\\Mmh-D02a.inf",
		"char\\tmABCD\\Mmh-D03a.inf",
		"char\\tmABCD\\Mmh-D04a.inf",
		"char\\tmABCD\\Mmh-D05a.inf",
		"char\\tmABCD\\Mmh-D06a.inf",
		"char\\tmABCD\\Mmh-D07a.inf",
		"char\\tmABCD\\Mmh-D08a.inf",
		"char\\tmABCD\\Mmh-D09a.inf",
		"char\\tmABCD\\Mmh-D10a.inf",
		"char\\tmABCD\\Mmh-D11a.inf",
		"char\\tmABCD\\Mmh-D12a.inf",
		"char\\tmABCD\\Mmh-D13a.inf",
		"char\\tmABCD\\MmhD14t.inf",
		"char\\tmABCD\\MmhD15t.inf",
		"char\\tmABCD\\MmhD16t.inf",
		"char\\tmABCD\\MmhD17t.inf",
		"char\\tmABCD\\Mmh-D19.inf",
		"char\\tmABCD\\Mmh-D20.inf",
		"char\\tmABCD\\Mmh-D21.inf",
		"char\\tmABCD\\Mmh-D22.inf",
		"char\\tmABCD\\Mmh-D23.inf",
		"char\\tmABCD\\Mmh-D24.inf",
		"char\\tmABCD\\Mmh-D25.inf",
		"char\\tmABCD\\Mmh-D26.inf",
		"char\\tmABCD\\hmage_02.inf",
		"char\\tmABCD\\hmage_03.inf",
		"char\\tmABCD\\CartolaMG.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\Mmh-D99.inf",
		"char\\tmABCD\\mgxmas.inf",
		"char\\tmABCD\\CarnivalHatMG.inf",
		"char\\tmABCD\\Mmh-D26.inf"
	},
	{
		"char\\tmABCD\\Mmh_D01b.inf",
		"char\\tmABCD\\Mmh_D02b.inf",
		"char\\tmABCD\\Mmh_D03b.inf",
		"char\\tmABCD\\Mmh_D04b.inf",
		"char\\tmABCD\\Mmh_D05b.inf",
		"char\\tmABCD\\Mmh_D06b.inf",
		"char\\tmABCD\\Mmh_D07b.inf",
		"char\\tmABCD\\Mmh_D08b.inf",
		"char\\tmABCD\\Mmh_D09b.inf",
		"char\\tmABCD\\Mmh_D10b.inf",
		"char\\tmABCD\\Mmh_D11b.inf",
		"char\\tmABCD\\Mmh_D12b.inf",
		"char\\tmABCD\\Mmh_D13b.inf",
		"char\\tmABCD\\MmhD14t.inf",
		"char\\tmABCD\\MmhD15t.inf",
		"char\\tmABCD\\MmhD16t.inf",
		"char\\tmABCD\\MmhD17t.inf",
		"char\\tmABCD\\Mmh-D19.inf",
		"char\\tmABCD\\Mmh-D20.inf",
		"char\\tmABCD\\Mmh-D21.inf",
		"char\\tmABCD\\Mmh-D22.inf",
		"char\\tmABCD\\Mmh-D23.inf",
		"char\\tmABCD\\Mmh-D24.inf",
		"char\\tmABCD\\Mmh-D25.inf",
		"char\\tmABCD\\Mmh-D26.inf",
		"char\\tmABCD\\hmage_02.inf",
		"char\\tmABCD\\hmage_03.inf",
		"char\\tmABCD\\CartolaMG.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\Mmh-D99.inf",
		"char\\tmABCD\\mgxmas.inf",
		"char\\tmABCD\\CarnivalHatMG.inf",
		"char\\tmABCD\\Mmh-D26.inf"
	},
	{
		"char\\tmABCD\\Mmh-D01c.inf",
		"char\\tmABCD\\Mmh-D02c.inf",
		"char\\tmABCD\\Mmh-D03c.inf",
		"char\\tmABCD\\Mmh-D04c.inf",
		"char\\tmABCD\\Mmh-D05c.inf",
		"char\\tmABCD\\Mmh-D06c.inf",
		"char\\tmABCD\\Mmh-D07c.inf",
		"char\\tmABCD\\Mmh-D08c.inf",
		"char\\tmABCD\\Mmh-D09c.inf",
		"char\\tmABCD\\Mmh-D10c.inf",
		"char\\tmABCD\\Mmh-D11c.inf",
		"char\\tmABCD\\Mmh-D12c.inf",
		"char\\tmABCD\\Mmh-D13c.inf",
		"char\\tmABCD\\MmhD14t.inf",
		"char\\tmABCD\\MmhD15t.inf",
		"char\\tmABCD\\MmhD16t.inf",
		"char\\tmABCD\\MmhD17t.inf",
		"char\\tmABCD\\Mmh-D19.inf",
		"char\\tmABCD\\Mmh-D20.inf",
		"char\\tmABCD\\Mmh-D21.inf",
		"char\\tmABCD\\Mmh-D22.inf",
		"char\\tmABCD\\Mmh-D23.inf",
		"char\\tmABCD\\Mmh-D24.inf",
		"char\\tmABCD\\Mmh-D25.inf",
		"char\\tmABCD\\Mmh-D26.inf",
		"char\\tmABCD\\hmage_02.inf",
		"char\\tmABCD\\hmage_03.inf",
		"char\\tmABCD\\CartolaMG.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\Mmh-D99.inf",
		"char\\tmABCD\\mgxmas.inf",
		"char\\tmABCD\\CarnivalHatMG.inf",
		"char\\tmABCD\\Mmh-D26.inf"
	},
	{
		"char\\tmABCD\\Mmh-D01d.inf",
		"char\\tmABCD\\Mmh-D02d.inf",
		"char\\tmABCD\\Mmh-D03d.inf",
		"char\\tmABCD\\Mmh-D04d.inf",
		"char\\tmABCD\\Mmh-D05d.inf",
		"char\\tmABCD\\Mmh-D06d.inf",
		"char\\tmABCD\\Mmh-D07d.inf",
		"char\\tmABCD\\Mmh-D08d.inf",
		"char\\tmABCD\\Mmh-D09d.inf",
		"char\\tmABCD\\Mmh-D10d.inf",
		"char\\tmABCD\\Mmh-D11d.inf",
		"char\\tmABCD\\Mmh-D12d.inf",
		"char\\tmABCD\\Mmh-D13d.inf",
		"char\\tmABCD\\MmhD14t.inf",
		"char\\tmABCD\\MmhD15t.inf",
		"char\\tmABCD\\MmhD16t.inf",
		"char\\tmABCD\\MmhD17t.inf",
		"char\\tmABCD\\Mmh-D19.inf",
		"char\\tmABCD\\Mmh-D20.inf",
		"char\\tmABCD\\Mmh-D21.inf",
		"char\\tmABCD\\Mmh-D22.inf",
		"char\\tmABCD\\Mmh-D23.inf",
		"char\\tmABCD\\Mmh-D24.inf",
		"char\\tmABCD\\Mmh-D25.inf",
		"char\\tmABCD\\Mmh-D26.inf",
		"char\\tmABCD\\hmage_02.inf",
		"char\\tmABCD\\hmage_03.inf",
		"char\\tmABCD\\CartolaMG.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\Mmh-D99.inf",
		"char\\tmABCD\\mgxmas.inf",
		"char\\tmABCD\\CarnivalHatMG.inf",
		"char\\tmABCD\\Mmh-D26.inf"
	},
	{
		"char\\tmABCD\\Mmh-D01b.inf",
		"char\\tmABCD\\Mmh-D02b.inf",
		"char\\tmABCD\\Mmh-D03b.inf",
		"char\\tmABCD\\Mmh-D01b.inf",
		"char\\tmABCD\\Mmh-D02b.inf",
		"char\\tmABCD\\Mmh-D03b.inf",
		"char\\tmABCD\\Mmh-D01b.inf",
		"char\\tmABCD\\Mmh-D02b.inf",
		"char\\tmABCD\\Mmh-D03b.inf",
		"char\\tmABCD\\Mmh-D01b.inf",
		"char\\tmABCD\\Mmh-D02b.inf",
		"char\\tmABCD\\Mmh-D03b.inf",
		"char\\tmABCD\\Mmh-D01b.inf",
		"char\\tmABCD\\Mmh-D01b.inf",
		"char\\tmABCD\\Mmh-D02b.inf",
		"char\\tmABCD\\Mmh-D03b.inf",
		"char\\tmABCD\\Mmh-D01b.inf",
		"char\\tmABCD\\Mmh-D02b.inf",
		"char\\tmABCD\\Mmh-D03b.inf",
		"char\\tmABCD\\Mmh-D01b.inf",
		"char\\tmABCD\\Mmh-D02b.inf",
		"char\\tmABCD\\Mmh-D03b.inf",
		"char\\tmABCD\\Mmh-D24.inf",
		"char\\tmABCD\\Mmh-D25.inf",
		"char\\tmABCD\\Mmh-D26.inf",
		"char\\tmABCD\\hmage_02.inf",
		"char\\tmABCD\\hmage_03.inf",
		"char\\tmABCD\\CartolaMG.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\Mmh-D99.inf",
		"char\\tmABCD\\mgxmas.inf",
		"char\\tmABCD\\CarnivalHatMG.inf",
		"char\\tmABCD\\Mmh-D26.inf"
	},
	{
		"char\\tmABCD\\Mmh-D01t.inf",
		"char\\tmABCD\\Mmh-D02t.inf",
		"char\\tmABCD\\Mmh-D03t.inf",
		"char\\tmABCD\\Mmh-D01t.inf",
		"char\\tmABCD\\Mmh-D02t.inf",
		"char\\tmABCD\\Mmh-D03t.inf",
		"char\\tmABCD\\Mmh-D01t.inf",
		"char\\tmABCD\\Mmh-D02t.inf",
		"char\\tmABCD\\Mmh-D01t.inf",
		"char\\tmABCD\\Mmh-D02t.inf",
		"char\\tmABCD\\Mmh-D03t.inf",
		"char\\tmABCD\\Mmh-D01t.inf",
		"char\\tmABCD\\Mmh-D02t.inf",
		"char\\tmABCD\\Mmh-D03t.inf",
		"char\\tmABCD\\Mmh-D01t.inf",
		"char\\tmABCD\\Mmh-D02t.inf",
		"char\\tmABCD\\Mmh-D03t.inf",
		"char\\tmABCD\\Mmh-D01t.inf",
		"char\\tmABCD\\Mmh-D02t.inf",
		"char\\tmABCD\\Mmh-D03t.inf",
		"char\\tmABCD\\Mmh-D01t.inf",
		"char\\tmABCD\\Mmh-D02t.inf",
		"char\\tmABCD\\Mmh-D24.inf",
		"char\\tmABCD\\Mmh-D25.inf",
		"char\\tmABCD\\Mmh-D26.inf",
		"char\\tmABCD\\hmage_02.inf",
		"char\\tmABCD\\hmage_03.inf",
		"char\\tmABCD\\CartolaMG.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\Mmh-D99.inf",
		"char\\tmABCD\\mgxmas.inf",
		"char\\tmABCD\\CarnivalHatMG.inf",
		"char\\tmABCD\\Mmh-D26.inf"
	},
	{
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\Mmh-D24.inf",
		"char\\tmABCD\\Mmh-D25.inf",
		"char\\tmABCD\\Mmh-D26.inf",
		"char\\tmABCD\\hmage_02.inf",
		"char\\tmABCD\\hmage_03.inf",
		"char\\tmABCD\\CartolaMG.inf",
		"char\\tmABCD\\MmhD-18t.inf",
		"char\\tmABCD\\Mmh-D99.inf",
		"char\\tmABCD\\mgxmas.inf",
		"char\\tmABCD\\CarnivalHatMG.inf",
		"char\\tmABCD\\Mmh-D26.inf"
	}
};

#define	ARMOR_FILE_MAX		200

char* szArmorNumFile[10][ARMOR_FILE_MAX] = {
	{	//MECHANICIAN 
		"A001.ini",  "A001.ini",  "A002.ini",  "A003.ini",  "A004.ini",  "A005.ini",  "A006.ini",  "A007.ini",  "A008.ini",  "A009.ini",
		"A010.ini",  "A011.ini",  "A012.ini",  "A013.ini",  "A014.ini",  "A015.ini",  "A016.ini",  "A017.ini",  "A018.ini",  "A019.ini",
		"A020.ini",  "A021.ini",  "A122.ini",  "A022.ini",  "A023.ini",  "A024.ini",  "A026.ini",  "A027.ini",  "A028.ini",  "A029.ini",
		"A030.ini",  "A031.ini",  "A032.ini",  "A029.ini",   "A030.ini","A031.ini","A101.ini",
		// Trajes (Armaduras)
		"A001.ini",  "A001.ini", "cA050.ini", "cA051.ini", "A101.ini", "A341.ini",
		"Ca001.ini", "Ca001.ini", "Ca001.ini", "Ca005.ini", "Ca023.ini", "Ca001.ini", "Ca001.ini", "Ca001.ini", "Ca001.ini", "Ca001.ini",
		"Ca001.ini", "Ca001.ini", "Ca001.ini", "Ca001.ini", "Ca001.ini", "Ca001.ini", "Ca001.ini",
		// Trajes (T)
		"Ca035.ini", "Ca004.ini", "Ca037.ini", "Ca029.ini", "Ca030.ini", "Ca031.ini", "Ca091.ini", "Ca038.ini", "Ca039.ini", "Ca034.ini",
		"Ca013.ini", "Ca014.ini", "Ca015.ini", "Ca017.ini", "Ca026.ini", "Ca040.ini",
	},
	{	//FIGHTER 
		"B001.ini",  "B001.ini",  "B002.ini",  "B003.ini",  "B004.ini",  "B005.ini",  "B006.ini",  "B007.ini",  "B008.ini",  "B009.ini",
		"B010.ini",  "B011.ini",  "B012.ini",  "B013.ini",  "B014.ini",  "B015.ini",  "B016.ini",  "B017.ini",  "B018.ini",  "B019.ini",
		"B020.ini",  "B021.ini",  "B122.ini",  "B022.ini",  "B023.ini",  "B024.ini",  "B026.ini",  "B027.ini",  "B028.ini",  "B029.ini",
		"b116.ini",  "B031.ini",  "B032.ini",	"B029.ini","B101.ini","B031.ini",  "B101.ini", "Cb002.ini", "B001.ini", "Cb050.ini",
		// Trajes (Armaduras)
		"cb051.ini", "b101.ini", "B341.ini",
		"Cb001.ini", "Cb001.ini", "Cb001.ini", "Cb005.ini", "Cb023.ini", "Cb001.ini", "Cb001.ini", "Cb001.ini", "Cb001.ini", "Cb001.ini",
		"Cb001.ini", "Cb001.ini", "Cb001.ini", "Cb001.ini", "Cb001.ini", "Cb001.ini", "Cb001.ini",
		// Trajes (T)
		"Cb035.ini", "Cb004.ini", "Cb037.ini", "Cb029.ini", "Cb030.ini", "Cb031.ini", "Cb091.ini", "Cb038.ini", "Cb039.ini", "Cb034.ini",
		"Cb013.ini", "Cb014.ini", "Cb015.ini", "Cb017.ini", "Cb026.ini", "Cb040.ini",
	},
	{	//PIKEMAN 
		"C001.ini",  "C001.ini",  "C002.ini",  "C003.ini",  "C004.ini",  "C005.ini",  "C006.ini",  "C007.ini",  "C008.ini",  "C009.ini",
		"C010.ini",  "C011.ini",  "C012.ini",  "C013.ini",  "C014.ini",  "C015.ini",  "C016.ini",  "C017.ini",  "C018.ini",  "C019.ini",
		"C020.ini",  "C021.ini",  "C122.ini",  "C022.ini",  "C023.ini",  "C024.ini",  "C026.ini",  "C027.ini",  "C028.ini",  "C029.ini",
		"C030.ini",  "C031.ini",  "C032.ini","C029.ini", "C030.ini", "C031.ini", "C101.ini",
		// Trajes (Armaduras)
		"C001.ini",  "Cc001.ini", "Cc050.ini", "Cc051.ini", "C101.ini", "C341.ini",
		"Cc001.ini", "Cc001.ini", "Cc001.ini", "Cc005.ini", "Cc023.ini", "Cc001.ini", "Cc001.ini", "Cc001.ini", "Cc001.ini", "Cc001.ini",
		"Cc001.ini", "Cc001.ini", "Cc001.ini", "Cc001.ini", "Cc001.ini", "Cc001.ini", "Cc001.ini",
		// Trajes (T)
		"Cc035.ini", "Cc004.ini", "Cc037.ini", "Cc029.ini", "Cc030.ini", "Cc031.ini", "Cc091.ini", "Cc038.ini", "Cc039.ini", "Cc034.ini",
		"Cc013.ini", "Cc014.ini", "Cc015.ini", "Cc017.ini", "Cc026.ini", "Cc040.ini",
	},
	{	//ARCHER
		"D001.ini",  "D001.ini",  "D002.ini",  "D003.ini",  "D004.ini",  "D005.ini",  "D006.ini",  "D007.ini",  "D008.ini",  "D009.ini",
		"D010.ini",  "D011.ini",  "D012.ini",  "D013.ini",  "D014.ini",  "D015.ini",  "D016.ini",  "D017.ini",  "D018.ini",  "D019.ini",
		"D020.ini",  "D021.ini",  "D122.ini",  "D022.ini",  "D023.ini",  "D024.ini",  "D026.ini",  "D027.ini",  "D028.ini",	 "D029.ini",
		"D030.ini",  "D031.ini",  "D032.ini",  "D029.ini",  "D030.ini", "D031.ini", "D101.ini",
		// Trajes (Armaduras)
		"D001.ini",  "Cd001.ini", "Cd050.ini", "Cd051.ini", "D101.ini", "D341.ini",
		"Cd001.ini", "Cd001.ini", "Cd001.ini", "Cd005.ini", "Cd023.ini", "Cd001.ini", "Cd001.ini", "Cd001.ini", "Cd001.ini", "Cd001.ini",
		"Cd001.ini", "Cd001.ini", "Cd001.ini", "Cd001.ini", "Cd001.ini", "Cd001.ini", "Cd001.ini",
		// Trajes (T)
		"Cd035.ini", "Cd004.ini", "Cd037.ini", "Cd029.ini", "Cd030.ini", "Cd031.ini", "Cd091.ini", "Cd038.ini", "Cd039.ini", "Cd034.ini",
		"Cd013.ini", "Cd014.ini", "Cd015.ini", "Cd017.ini", "Cd026.ini", "Cd040.ini",
	},

	{	//KNIGHT 
		"mA001.ini",  "mA001.ini",  "mA002.ini",  "mA003.ini",  "mA004.ini",  "mA005.ini",  "mA006.ini",  "mA007.ini",  "mA008.ini",  "mA009.ini",
		"mA010.ini",  "mA011.ini",  "mA012.ini",  "mA013.ini",  "mA014.ini",  "mA015.ini",  "mA016.ini",  "mA017.ini",  "mA018.ini",  "mA019.ini",
		"mA020.ini",  "mA021.ini",  "mA122.ini",  "mA022.ini",  "mA023.ini",  "mA024.ini",  "mA026.ini",  "mA027.ini",  "mA028.ini",  "mA029.ini",
		"mA030.ini",  "mA031.ini",  "mA032.ini",  "mA029.ini",  "mA030.ini",  "mA031.ini", "mA101.ini",
		// Trajes (Armaduras)
		"mA001.ini",   "Cma001.ini", "Cma050.ini", "Cma051.ini", "mA101.ini", "mA341.ini",
		"Cma001.ini", "Cma001.ini", "Cma001.ini", "Cma005.ini", "Cma023.ini", "Cma001.ini", "Cma001.ini", "Cma001.ini", "Cma001.ini", "Cma001.ini",
		"Cma001.ini", "Cma001.ini", "Cma001.ini", "Cma001.ini", "Cma001.ini", "Cma001.ini", "Cma001.ini",
		// Trajes (T)
		"Cma035.ini", "Cma004.ini", "Cma037.ini", "Cma029.ini", "Cma030.ini", "Cma031.ini", "Cma091.ini", "Cma038.ini", "Cma039.ini", "Cma034.ini",
		"Cma013.ini", "Cma014.ini", "Cma015.ini", "Cma017.ini", "Cma026.ini", "Cma040.ini",
	},
	{	//ATALANTA 
		"mB001.ini",  "mB001.ini",  "mB002.ini",  "mB003.ini",  "mB004.ini",  "mB005.ini",  "mB006.ini",  "mB007.ini",  "mB008.ini",  "mB009.ini",
		"mB010.ini",  "mB011.ini",  "mB012.ini",  "mB013.ini",  "mB014.ini",  "mB015.ini",  "mB016.ini",  "mB017.ini",  "mB018.ini",  "mB019.ini",
		"mB020.ini",  "mB021.ini",  "mB122.ini",  "mB022.ini",  "mB023.ini",  "mB024.ini",  "mB026.ini",  "mB027.ini",  "mB028.ini",  "mB029.ini",
		"mB030.ini",  "mB031.ini",  "mB032.ini",  "mB029.ini",  "mB030.ini", "mB031.ini", "mB101.ini",
		// Trajes (Armaduras)
		"mB001.ini",  "Cmb001.ini", "Cmb050.ini", "Cmb051.ini", "mB101.ini", "mB341.ini",
		"Cmb001.ini", "Cmb001.ini", "Cmb001.ini", "Cmb005.ini", "Cmb023.ini", "Cmb001.ini", "Cmb001.ini", "Cmb001.ini", "Cmb001.ini", "Cmb001.ini",
		"Cmb001.ini", "Cmb001.ini", "Cmb001.ini", "Cmb001.ini", "Cmb001.ini", "Cmb001.ini", "Cmb001.ini",
		// Trajes (T)
		"Cmb035.ini", "Cmb004.ini", "Cmb037.ini", "Cmb029.ini", "Cmb030.ini", "Cmb031.ini", "Cmb091.ini", "Cmb038.ini", "Cmb039.ini", "Cmb034.ini",
		"Cmb013.ini", "Cmb014.ini", "Cmb015.ini", "Cmb017.ini", "Cmb026.ini", "Cmb040.ini",
	},
	{	//PRIESTESS
		"mC001.ini",  "mC001.ini",  "mC002.ini",  "mC003.ini",  "mC004.ini",  "mC005.ini",  "mC006.ini",  "mC007.ini",  "mC008.ini",  "mC009.ini",
		"mC010.ini",  "mC011.ini",  "mC012.ini",  "mC013.ini",  "mC014.ini",  "mC015.ini",  "mC016.ini",  "mC017.ini",  "mC018.ini",  "mC019.ini",
		"mC020.ini",  "mC021.ini",  "mC122.ini",  "mC022.ini",  "mC023.ini",  "mC024.ini",  "mC026.ini",  "mC027.ini",  "mC028.ini",  "mC029.ini",
		"mC030.ini",  "mC031.ini",  "mC032.ini", "mC029.ini", "mC030.ini", "mC031.ini", "mC101.ini",
		// Trajes (Armaduras)
		"mC001.ini", "Cmc001.ini", "Cmc050.ini", "Cmc051.ini", "mC101.ini", "mC441.ini",
		"Cmc001.ini", "Cmc001.ini", "Cmc001.ini", "Cmc005.ini", "Cmc023.ini", "Cmc001.ini", "Cmc001.ini", "Cmc001.ini", "Cmc001.ini", "Cmc001.ini",
		"Cmc001.ini", "Cmc001.ini", "Cmc001.ini", "Cmc001.ini", "Cmc001.ini", "Cmc001.ini", "Cmc001.ini",
		// Trajes (T)
		"Cmc035.ini", "Cmc004.ini", "Cmc037.ini", "Cmc029.ini", "Cmc030.ini", "Cmc031.ini", "Cmc091.ini", "Cmc038.ini", "Cmc039.ini", "Cmc034.ini",
		"Cmc013.ini", "Cmc014.ini", "Cmc015.ini", "Cmc017.ini", "Cmc026.ini", "Cmc040.ini",
	},
	{	//MAGICIAN 
		"mD001.ini",  "mD001.ini",  "mD002.ini",  "mD003.ini",  "mD004.ini",  "mD005.ini",  "mD006.ini",  "mD007.ini",  "mD008.ini",  "mD009.ini",
		"mD010.ini",  "mD011.ini",  "mD012.ini",  "mD013.ini",  "mD014.ini",  "mD015.ini",  "mD016.ini",  "mD017.ini",  "mD018.ini",  "mD019.ini",
		"mD020.ini",  "mD021.ini",  "mD122.ini",  "mD022.ini",  "mD023.ini",  "mD024.ini",  "mD026.ini",  "mD027.ini",  "mD028.ini",  "mD029.ini",
		"mD030.ini",  "mD031.ini",  "mD032.ini",  "mD029.ini",  "mD030.ini", "mD031.ini",  "mD101.ini",
		// Trajes (Armaduras)
		"mD001.ini",   "Cmd001.ini", "Cmd050.ini", "Cmd051.ini", "mD101.ini", "mD441.ini",
		"Cmd001.ini", "Cmd001.ini", "Cmd001.ini", "Cmd005.ini", "Cmd023.ini", "Cmd001.ini", "Cmd001.ini", "Cmd001.ini", "Cmd001.ini", "Cmd001.ini",
		"Cmd001.ini", "Cmd001.ini", "Cmd001.ini", "Cmd001.ini", "Cmd001.ini", "Cmd001.ini", "Cmd001.ini",
		// Trajes (T)
		"Cmd035.ini", "Cmd004.ini", "Cmd037.ini", "Cmd029.ini", "Cmd030.ini", "Cmd031.ini", "Cmd091.ini", "Cmd038.ini", "Cmd039.ini", "Cmd034.ini",
		"Cmd013.ini", "Cmd014.ini", "Cmd015.ini", "Cmd017.ini", "Cmd026.ini", "Cmd040.ini",
	},
};

char* szArmorNumFile_Comic[10][ARMOR_FILE_MAX] = {
	{ "A001.ini" , "A001.ini",  "A002.ini",  "A003.ini",  "A004.ini",  "A005.ini",  "A006.ini",  "A007.ini", "A008.ini", "A009.ini", "A010.ini",
	"A011.ini" , "A012.ini",  "A013.ini",  "A014.ini",  "A015.ini",  "A016.ini",  "A017.ini",  "A018.ini", "A019.ini", "A020.ini", "A021.ini",
	"A001.ini" , "A022.ini",  "A023.ini",  "A024.ini",  "A001.ini",  "A001.ini",  "A001.ini",  "A001.ini",
	"Ca001.ini", "Ca001.ini", "Ca001.ini", "Ca001.ini", "Ca002.ini", "Ca002.ini", "Ca002.ini", "Ca002.ini",
	"Ca003.ini", "Ca003.ini", "Ca003.ini", "Ca003.ini", "Ca004.ini", "Ca004.ini", "Ca004.ini", "Ca004.ini",
	"Ca005.ini", "Ca006.ini", "Ca007.ini", "Ca008.ini", "Ca009.ini", "Ca010.ini", "Ca011.ini", "Ca012.ini"
	},

	{ "B001.ini" , "B001.ini",  "B002.ini",  "B003.ini",  "B004.ini" , "B005.ini",  "B006.ini",  "B007.ini", "B008.ini", "B009.ini", "B010.ini" ,
	"B011.ini" , "B012.ini",  "B013.ini",  "B014.ini",  "B015.ini" , "B016.ini",  "B017.ini",  "B018.ini", "B019.ini", "B020.ini", "B021.ini" ,
	"B001.ini" , "B022.ini",  "B023.ini",  "B024.ini",  "B001.ini",  "B001.ini" , "B001.ini" , "B001.ini",
	"Cb001.ini", "Cb001.ini", "Cb001.ini", "Cb001.ini", "Cb002.ini", "Cb002.ini", "Cb002.ini", "Cb002.ini",
	"Cb003.ini", "Cb003.ini", "Cb003.ini", "Cb003.ini", "Cb004.ini", "Cb004.ini", "Cb004.ini", "Cb004.ini",
	"Cb005.ini", "Cb006.ini", "Cb007.ini", "Cb008.ini", "Cb009.ini", "Cb010.ini", "Cb011.ini", "Cb012.ini"
	},

	{ "C001.ini" , "C001.ini",  "C002.ini",  "C003.ini",  "C004.ini",  "C005.ini",  "C006.ini",  "C007.ini",  "C008.ini", "C009.ini", "C010.ini",
	"C011.ini" , "C012.ini",  "C013.ini",  "C014.ini",  "C015.ini",  "C016.ini",  "C017.ini",  "C018.ini",  "C019.ini", "C020.ini", "C021.ini",
	"C001.ini" , "C022.ini",  "C023.ini",  "C024.ini",  "C001.ini",  "C001.ini",  "C001.ini",  "C001.ini",
	"Cc001.ini", "Cc001.ini", "Cc001.ini", "Cc001.ini", "Cc002.ini", "Cc002.ini", "Cc002.ini", "Cc002.ini",
	"Cc003.ini", "Cc003.ini", "Cc003.ini", "Cc003.ini", "Cc004.ini", "Cc004.ini", "Cc004.ini", "Cc004.ini",
	"Cc005.ini", "Cc006.ini", "Cc007.ini", "Cc008.ini", "Cc009.ini", "Cc010.ini", "Cc011.ini", "Cc012.ini"
	},

	{ "D001.ini" , "D001.ini",  "D002.ini",  "D003.ini",  "D004.ini",  "D005.ini",  "D006.ini",  "D007.ini", "D008.ini", "D009.ini", "D010.ini",
	"D011.ini" , "D012.ini",  "D013.ini",  "D014.ini",  "D015.ini",  "D016.ini",  "D017.ini",  "D018.ini", "D019.ini", "D020.ini", "D021.ini",
	"D001.ini" , "D022.ini",  "D023.ini",  "D024.ini",  "D001.ini",  "D001.ini",  "D001.ini",  "D001.ini",
	"Cd001.ini", "Cd001.ini", "Cd001.ini", "Cd001.ini", "Cd002.ini", "Cd002.ini", "Cd002.ini", "Cd002.ini",
	"Cd003.ini", "Cd003.ini", "Cd003.ini", "Cd003.ini", "Cd004.ini", "Cd004.ini", "Cd004.ini", "Cd004.ini",
	"Cd005.ini", "Cd006.ini", "Cd007.ini", "Cd008.ini", "Cd009.ini", "Cd010.ini", "Cd011.ini", "Cd012.ini"
	},

	{ "mA001.ini",  "mA001.ini",  "mA002.ini",  "mA003.ini",   "mA004.ini",  "mA005.ini",  "mA006.ini",  "mA007.ini", "mA008.ini", "mA009.ini", "mA010.ini",
	"mA011.ini",  "mA012.ini",  "mA013.ini",  "mA014.ini",   "mA015.ini",  "mA016.ini",  "mA017.ini",  "mA018.ini", "mA019.ini", "mA020.ini", "mA021.ini",
	"mA001.ini",  "mA022.ini",  "mA023.ini",  "mA024.ini",  "mA001.ini",   "mA001.ini",  "mA001.ini",  "mA001.ini",
	"Cma001.ini", "Cma001.ini", "Cma001.ini", "Cma001.ini",  "Cma002.ini", "Cma002.ini", "Cma002.ini", "Cma002.ini",
	"Cma003.ini", "Cma003.ini", "Cma003.ini", "Cma003.ini",  "Cma004.ini", "Cma004.ini", "Cma004.ini", "Cma004.ini",
	"Cma005.ini", "Cma006.ini", "Cma007.ini", "Cma008.ini",  "Cma009.ini",  "Cma010.ini", "Cma011.ini", "Cma012.ini"
	},

	{ "mB001.ini",  "mB001.ini",  "mB002.ini",  "mB003.ini",  "mB004.ini",  "mB005.ini",  "mB006.ini",  "mB007.ini", "mB008.ini", "mB009.ini", "mB010.ini",
	"mB011.ini",  "mB012.ini",  "mB013.ini",  "mB014.ini",  "mB015.ini",  "mB016.ini",  "mB017.ini",  "mB018.ini", "mB019.ini", "mB020.ini", "mB021.ini",
	"mB001.ini",  "mB022.ini",  "mB023.ini",  "mB024.ini" , "mB001.ini",  "mB001.ini",  "mB001.ini" , "mB001.ini" ,
	"Cmb001.ini", "Cmb001.ini", "Cmb001.ini", "Cmb001.ini", "Cmb002.ini", "Cmb002.ini", "Cmb002.ini", "Cmb002.ini",
	"Cmb003.ini", "Cmb003.ini", "Cmb003.ini", "Cmb003.ini", "Cmb004.ini", "Cmb004.ini", "Cmb004.ini", "Cmb004.ini",
	"Cmb005.ini", "Cmb006.ini", "Cmb007.ini", "Cmb008.ini", "Cmb009.ini", "Cmb010.ini", "Cmb011.ini", "Cmb012.ini"
	},

	{ "mC001.ini",  "mC001.ini",  "mC002.ini",  "mC003.ini",  "mC004.ini",  "mC005.ini",  "mC006.ini",  "mC007.ini", "mC008.ini", "mC009.ini", "mC010.ini",
	"mC011.ini",  "mC012.ini",  "mC013.ini",  "mC014.ini",  "mC015.ini",  "mC016.ini",  "mC017.ini",  "mC018.ini", "mC019.ini", "mC020.ini", "mC021.ini",
	"mC001.ini",  "mC022.ini",  "mC023.ini",  "mC024.ini",  "mC001.ini",  "mC001.ini",  "mC001.ini",  "mC001.ini",
	"Cmc001.ini", "Cmc001.ini", "Cmc001.ini", "Cmc001.ini", "Cmc002.ini", "Cmc002.ini", "Cmc002.ini", "Cmc002.ini",
	"Cmc003.ini", "Cmc003.ini", "Cmc003.ini", "Cmc003.ini", "Cmc004.ini", "Cmc004.ini", "Cmc004.ini", "Cmc004.ini",
	"Cmc005.ini", "Cmc006.ini", "Cmc007.ini", "Cmc008.ini", "Cmc009.ini", "Cmc010.ini", "Cmc011.ini", "Cmc012.ini"
	},

	{ "mD001.ini",  "mD001.ini",  "mD002.ini",  "mD003.ini",  "mD004.ini",  "mD005.ini",  "mD006.ini",  "mD007.ini", "mD008.ini", "mD009.ini", "mD010.ini",
	"mD011.ini",  "mD012.ini",  "mD013.ini",  "mD014.ini",  "mD015.ini",  "mD016.ini",  "mD017.ini",  "mD018.ini", "mD019.ini", "mD020.ini", "mD021.ini",
	"mD001.ini",  "mD022.ini",  "mD023.ini",  "mD024.ini",  "mD001.ini",  "mD001.ini",  "mD001.ini",  "mD001.ini",
	"Cmd001.ini", "Cmd001.ini", "Cmd001.ini", "Cmd001.ini", "Cmd002.ini", "Cmd002.ini", "Cmd002.ini", "Cmd002.ini",
	"Cmd003.ini", "Cmd003.ini", "Cmd003.ini", "Cmd003.ini", "Cmd004.ini", "Cmd004.ini", "Cmd004.ini", "Cmd004.ini",
	"Cmd005.ini", "Cmd006.ini", "Cmd007.ini", "Cmd008.ini", "Cmd009.ini", "Cmd010.ini", "Cmd011.ini", "Cmd012.ini"
	},
};